"""
Classical machine learning models for time series.
"""

from .base import ClassicalModel
from .boosting import (
    AdaBoostModel,
    GBRTModel,
    GradientBoostingModel,
    LightGBMModel,
    XGBoostModel,
)
from .ensemble import (
    BaggingModel,
    StackingModel,
    VotingModel,
    WeightedAverageModel,
)
from .linear import (
    ElasticNetModel,
    LARSModel,
    LassoRegressionModel,
    LinearRegressionModel,
    LOESSModel,
    LogisticRegressionModel,
    MARSModel,
    OLSRModel,
    PolynomialRegressionModel,
    RidgeRegressionModel,
    StepwiseRegressionModel,
)
from .naive_bayes import (
    AODEModel,
    BayesianNetworkModel,
    GaussianNaiveBayesModel,
    MultinomialNaiveBayesModel,
    NaiveBayesModel,
)
from .neighbors import LWLModel, kNNModel
from .svm import (
    LinearSVMModel,
    LSSVMModel,
    NuSVMModel,
    OneClassSVMModel,
    SVMModel,
    SVRModel,
    TWSVMModel,
)
from .trees import (
    C45Model,
    C50Model,
    CARTModel,
    CHAIDModel,
    ConditionalDecisionTreeModel,
    DecisionStumpModel,
    DecisionTreeModel,
    ID3Model,
    M5Model,
    RandomForestModel,
)

__all__ = [
    "AODEModel",
    "AdaBoostModel",
    "BaggingModel",
    "BayesianNetworkModel",
    "C45Model",
    "C50Model",
    "CARTModel",
    "CHAIDModel",
    "ClassicalModel",
    "ConditionalDecisionTreeModel",
    "DecisionStumpModel",
    "DecisionTreeModel",
    "ElasticNetModel",
    "GBRTModel",
    "GaussianNaiveBayesModel",
    "GradientBoostingModel",
    "ID3Model",
    "LARSModel",
    "LOESSModel",
    "LSSVMModel",
    "LWLModel",
    "LWLModel",
    "LassoRegressionModel",
    "LightGBMModel",
    "LinearRegressionModel",
    "LinearSVMModel",
    "LogisticRegressionModel",
    "M5Model",
    "MARSModel",
    "MultinomialNaiveBayesModel",
    "NaiveBayesModel",
    "NuSVMModel",
    "OLSRModel",
    "OneClassSVMModel",
    "PolynomialRegressionModel",
    "RandomForestModel",
    "RandomForestModel",
    "RidgeRegressionModel",
    "SVMModel",
    "SVRModel",
    "StackingModel",
    "StepwiseRegressionModel",
    "StepwiseRegressionModel",
    "TWSVMModel",
    "VotingModel",
    "WeightedAverageModel",
    "XGBoostModel",
    "kNNModel",
    "kNNModel",
]
