[project]
name = "nglab"
version = "0.1.0"
description = "A Multimodal Deep Reinforcement Learning bot to assist you in all your gambling (stock market) needs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.3",
    "ipykernel==6.25",
    "loss-landscapes>=3.0.6",
    "matplotlib==3.7",
    "maturin>=1.10.2",
    "numpy==1.24",
    "pandas==2.0",
    "pip==23.3",
    "pytorch-lightning==2.0",
    "requests==2.31",
    "rich>=14.2.0",
    "scipy==1.10",
    "stable-baselines3>=2.5.0",
    "tensorboard-logger==0.1",
    "torch>=2.3",
    "torch-geometric>=2.7.0",
    "torch-tb-profiler<=0.4.3",
    "torchmetrics>=1.0",
    "tqdm==4.65",
    "wandb==0.15",
    "yfinance==0.2.66",
]

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "nglab._nglab"
bindings = "pyo3"
manifest-path = "rust/Cargo.toml"

[tool.basedpyright]
typeCheckingMode = "basic"
include = ["python", "environment"]
reportUnusedImport = "warning"

# Create an override for __init__.py files
ignore = ["**/__init__.py"]

# Disables the "None is not assignable to type X" errors
reportOptionalSubscript = "none"
reportOptionalMemberAccess = "none"
reportOptionalCall = "none"
reportOptionalIterable = "none"

# Disable function calls, attribute access, operator issues and type checking
reportAttributeAccessIssue = "none"
reportGeneralTypeIssues = "none"
reportOperatorIssue = "none"
reportArgumentType = "none"
reportCallIssue = "none"
