"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec
from google.auth import _helpers
from google.auth.crypt import base

"""ECDSA verifier and signer that use the ``cryptography`` library.
"""
_CERTIFICATE_MARKER = ...
_BACKEND = ...
_PADDING = ...

@dataclass
class _ESAttributes:
    """A class that models ECDSA attributes.

    Attributes:
        rs_size (int): Size for ASN.1 r and s size.
        sha_algo (hashes.HashAlgorithm): Hash algorithm.
        algorithm (str): Algorithm name.
    """

    rs_size: int
    sha_algo: hashes.HashAlgorithm
    algorithm: str
    @classmethod
    def from_key(
        cls, key: Union[ec.EllipticCurvePublicKey, ec.EllipticCurvePrivateKey]
    ):  # -> Self:
        ...
    @classmethod
    def from_curve(cls, curve: ec.EllipticCurve):  # -> Self:
        ...

class EsVerifier(base.Verifier):
    """Verifies ECDSA cryptographic signatures using public keys.

    Args:
        public_key (
                cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicKey):
            The public key used to verify signatures.
    """

    def __init__(self, public_key: ec.EllipticCurvePublicKey) -> None: ...
    @_helpers.copy_docstring(base.Verifier)
    def verify(self, message: bytes, signature: bytes) -> bool: ...
    @classmethod
    def from_string(cls, public_key: Union[str, bytes]) -> EsVerifier:
        """Construct an Verifier instance from a public key or public
        certificate string.

        Args:
            public_key (Union[str, bytes]): The public key in PEM format or the
                x509 public key certificate.

        Returns:
            Verifier: The constructed verifier.

        Raises:
            ValueError: If the public key can't be parsed.
        """
        ...

class EsSigner(base.Signer, base.FromServiceAccountMixin):
    """Signs messages with an ECDSA private key.

    Args:
        private_key (
                cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey):
            The private key to sign with.
        key_id (str): Optional key ID used to identify this private key. This
            can be useful to associate the private key with its associated
            public key or certificate.
    """

    def __init__(
        self, private_key: ec.EllipticCurvePrivateKey, key_id: Optional[str] = ...
    ) -> None: ...
    @property
    def algorithm(self) -> str:
        """Name of the algorithm used to sign messages.
        Returns:
            str: The algorithm name.
        """
        ...

    @property
    @_helpers.copy_docstring(base.Signer)
    def key_id(self) -> Optional[str]: ...
    @_helpers.copy_docstring(base.Signer)
    def sign(self, message: bytes) -> bytes: ...
    @classmethod
    def from_string(
        cls, key: Union[bytes, str], key_id: Optional[str] = ...
    ) -> EsSigner:
        """Construct a RSASigner from a private key in PEM format.

        Args:
            key (Union[bytes, str]): Private key in PEM format.
            key_id (str): An optional key id used to identify the private key.

        Returns:
            google.auth.crypt._cryptography_rsa.RSASigner: The
            constructed signer.

        Raises:
            ValueError: If ``key`` is not ``bytes`` or ``str`` (unicode).
            UnicodeDecodeError: If ``key`` is ``bytes`` but cannot be decoded
                into a UTF-8 ``str``.
            ValueError: If ``cryptography`` "Could not deserialize key data."
        """
        ...

    def __getstate__(self) -> Dict[str, Any]:
        """Pickle helper that serializes the _key attribute."""
        ...

    def __setstate__(self, state: Dict[str, Any]) -> None:
        """Pickle helper that deserializes the _key attribute."""
        ...
