"""
Main Entry Point for NGLab Training Pipeline.

Integrates Hydra for configuration and PyTorch Lightning for scalable training
across Reinforcement Learning, Supervised Learning, and Unsupervised Learning tasks.
"""

import hydra
import pytorch_lightning as pl
from omegaconf import DictConfig, OmegaConf
from pytorch_lightning.loggers import TensorBoardLogger

from python.src.env.env_wrapper import TradingEnvWrapper

# Imports from our modules
from python.src.models.time_series import TimeSeriesBackbone
from python.src.pipeline.core.lightning.reinforcement_learning import RLLightningModule
from python.src.pipeline.core.lightning.self_supervised import SelfSupervisedModule
from python.src.pipeline.core.lightning.semi_supervised import SemiSupervisedModule
from python.src.pipeline.core.lightning.supervised_learning import SLLightningModule
from python.src.pipeline.core.lightning.unsupervised_learning import UnsupervisedModule
from python.src.pipeline.core.lightning.vae_module import VAELightningModule
from python.src.policies.neural import NeuralPolicy
from python.src.utils.profiling.profiling import profile


@hydra.main(version_base=None, config_path="conf", config_name="config")
@profile(output_dir="./profiles")
def main(cfg: DictConfig):
    """
    Main training function triggered by Hydra.
    """
    print(OmegaConf.to_yaml(cfg))
    pl.seed_everything(cfg.seed)

    # 1. Instantiate Backbone
    backbone = TimeSeriesBackbone(cfg.model)

    # 2. Select Task Module
    if cfg.task == "rl":
        # Environment
        def env_maker():
            """
            Factory function for creating environment instances.
            """
            return TradingEnvWrapper(**cfg.env)

        # Policy (Actor)
        policy = NeuralPolicy(backbone, cfg.model)  # Wrapping backbone

        # Value Network (Critic) - instantiated similarly or separate backbone
        # For simplicity reusing/instantiating backbone check cfg
        critic = TimeSeriesBackbone(cfg.model)

        model = RLLightningModule(
            agent_module=policy,
            value_module=critic,
            env_maker=env_maker,
            cfg=cfg.algorithm,
        )

    elif cfg.task == "unsupervised":
        model = UnsupervisedModule(backbone, cfg.model)  # Or conf for pretraining
    elif cfg.task == "self_supervised":
        model = SelfSupervisedModule(backbone, cfg.model)
    elif cfg.task == "semi_supervised":
        model = SemiSupervisedModule(backbone, cfg.model)
    elif cfg.task == "supervised":
        model = SLLightningModule(backbone, cfg.model)
    elif cfg.task == "vae":
        model = VAELightningModule(**cfg.model)
    else:
        raise ValueError(f"Unknown task: {cfg.task}")

    # 3. Trainer
    logger = TensorBoardLogger("tb_logs", name=cfg.task)
    trainer = pl.Trainer(
        max_epochs=cfg.max_epochs,
        accelerator=cfg.device,
        devices=1,
        logger=logger,
        gradient_clip_val=cfg.gradient_clip_val,
        val_check_interval=cfg.val_check_interval,
    )

    # 4. Fit
    # For RL, the dataloader is internal/generated by collector.
    # For others, we need a dataloader.
    # Placeholder for DataModule usage or passing dataloaders.
    # For RL LightningModule we implemented 'train_dataloader' so we can just call fit(model).

    if cfg.task == "rl":
        trainer.fit(model)
    else:
        # DataLoader for SL/SSL/UL tasks
        from python.src.data.dataloaders import create_dataloader

        # Get dataloader config (with defaults if not present)
        data_cfg = cfg.get("data", {})

        train_loader, val_loader, test_loader = create_dataloader(
            data_path=data_cfg.get("data_path", "data/polymarket/"),
            target_column=data_cfg.get("target_column", "price"),
            batch_size=data_cfg.get("batch_size", 32),
            seq_len=data_cfg.get("seq_len", 30),
            pred_len=data_cfg.get("pred_len", 1),
            train_ratio=data_cfg.get("train_ratio", 0.7),
            val_ratio=data_cfg.get("val_ratio", 0.15),
            test_ratio=data_cfg.get("test_ratio", 0.15),
            normalize=data_cfg.get("normalize", "minmax"),
            num_workers=data_cfg.get("num_workers", 4),
            format=data_cfg.get("format", "csv"),
            streaming=data_cfg.get("streaming", False),
            add_technical_indicators=data_cfg.get("add_technical_indicators", False),
        )

        trainer.fit(model, train_dataloaders=train_loader, val_dataloaders=val_loader)


if __name__ == "__main__":
    main()
