"""
This type stub file was generated by pyright.
"""

from typing import List, Optional

"""IP Filter configuration for Google Cloud Storage Buckets."""
_MODE = ...
_PUBLIC_NETWORK_SOURCE = ...
_VPC_NETWORK_SOURCES = ...
_ALLOWED_IP_CIDR_RANGES = ...
_NETWORK = ...
_ALLOW_ALL_SERVICE_AGENT_ACCESS = ...
_ALLOW_CROSS_ORG_VPCS = ...

class PublicNetworkSource:
    """Represents a public network source for a GCS Bucket IP Filter.

    :type allowed_ip_cidr_ranges: list(str) or None
    :param allowed_ip_cidr_ranges: A list of public IPv4 or IPv6 ranges in
                                   CIDR notation that are allowed to access
                                   the bucket.
    """

    def __init__(self, allowed_ip_cidr_ranges: Optional[List[str]] = ...) -> None: ...

class VpcNetworkSource:
    """Represents a VPC network source for a GCS Bucket IP Filter.

    :type network: str
    :param network: The resource name of the VPC network.

    :type allowed_ip_cidr_ranges: list(str) or None
    :param allowed_ip_cidr_ranges: A list of IPv4 or IPv6 ranges in CIDR
                                   notation allowed to access the bucket
                                   from this VPC.
    """

    def __init__(
        self, network: str, allowed_ip_cidr_ranges: Optional[List[str]] = ...
    ) -> None: ...

class IPFilter:
    """Represents a GCS Bucket IP Filter configuration.

    This class is a helper for constructing the IP Filter dictionary to be
    assigned to a bucket's ``ip_filter`` property.
    """

    def __init__(self) -> None: ...
