"""
This type stub file was generated by pyright.
"""

from google.api_core import (
    _python_package_support,
    _python_version_support,
    version as api_core_version,
)

"""Google API Core.

This package contains common code and utilities used by Google client libraries.
"""
__version__ = ...
check_python_version = ...
check_dependency_versions = ...
parse_version_to_tuple = ...
warn_deprecation_for_versions_less_than = ...
DependencyConstraint = _python_package_support.DependencyConstraint
