apiVersion: v1
kind: Service
metadata:
  name: nglab-api-service
  namespace: nglab
  labels:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: nglab-api-gpu-service
  namespace: nglab
  labels:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: api-gpu
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: api-gpu
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nglab
  labels:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nglab
  labels:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: nglab
    app.kubernetes.io/component: redis
