// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result containing the simulated ARIMA path.
 */
export type ArimaResult = { path: Array<number>, used_seed: bigint | null, };
