// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result containing the simulated ARIMA path.
 */
export type ArimaResult = { 
/**
 * The simulated time series path.
 */
path: Array<number>, 
/**
 * The actual seed used for the simulation.
 */
used_seed: bigint | null, };
