// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported order types.
 */
export type OrderType = "Limit" | "Market" | "StopLoss" | "TakeProfit" | "StopLimit" | "FillOrKill" | "ImmediateOrCancel" | "Pegged";
