// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderType } from "./OrderType";
import type { PegReference } from "./PegReference";
import type { Side } from "./Side";

/**
 * A single order entry in the book.
 */
export type Order = { 
/**
 * Unique identifier for the order
 */
id: bigint, 
/**
 * Price per unit
 */
price: number, 
/**
 * Total quantity to be traded
 */
quantity: number, 
/**
 * Quantity already filled
 */
filled: number, 
/**
 * Side of the market (Bid or Ask)
 */
side: Side, 
/**
 * Type of order (Limit, Market, etc.)
 */
order_type: OrderType, 
/**
 * Unix timestamp of order submission
 */
timestamp: bigint, 
/**
 * Price that triggers the order (for Stop/TakeProfit)
 */
trigger_price: number | null, 
/**
 * Total quantity for Iceberg orders
 */
iceberg_total: number | null, 
/**
 * Currently visible quantity for Iceberg orders
 */
visible_quantity: number | null, 
/**
 * Identifier of the parent order (for OCO)
 */
parent_id: bigint | null, 
/**
 * Delta for trailing stop orders
 */
trailing_delta: number | null, 
/**
 * Current trigger point for trailing stop orders
 */
current_trailing_price: number | null, 
/**
 * Unix timestamp when order expires
 */
expiry: bigint | null, 
/**
 * Sibling order ID for One-Cancels-Other (OCO)
 */
oco_id: bigint | null, 
/**
 * Stop loss price for bracket order
 */
bracket_sl: number | null, 
/**
 * Take profit price for bracket order
 */
bracket_tp: number | null, 
/**
 * Reference for pegged orders
 */
peg_reference: PegReference | null, 
/**
 * Offset for pegged orders
 */
peg_offset: number | null, };
