// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result container for Prophet forecasts.
 */
export type ProphetResult = { 
/**
 * Timestamps for the forecast period.
 */
times: Array<bigint>, 
/**
 * Total forecasted values (trend + seasonal).
 */
values: Array<number>, 
/**
 * Trend component of the forecast.
 */
trend: Array<number>, 
/**
 * Seasonality component of the forecast.
 */
seasonal: Array<number>, };
