// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result container for Prophet forecasts.
 */
export type ProphetResult = { times: Array<bigint>, values: Array<number>, trend: Array<number>, seasonal: Array<number>, };
