"""
This type stub file was generated by pyright.
"""

import sys
import google.api_core as api_core
import warnings
from google.cloud.storage_control_v2 import gapic_version as package_version
from importlib import metadata
from .services.storage_control import StorageControlAsyncClient, StorageControlClient
from .types.storage_control import (
    AnywhereCache,
    CommonLongRunningOperationMetadata,
    CreateAnywhereCacheMetadata,
    CreateAnywhereCacheRequest,
    CreateFolderRequest,
    CreateManagedFolderRequest,
    DeleteFolderRequest,
    DeleteManagedFolderRequest,
    DisableAnywhereCacheRequest,
    Folder,
    GetAnywhereCacheRequest,
    GetFolderIntelligenceConfigRequest,
    GetFolderRequest,
    GetManagedFolderRequest,
    GetOrganizationIntelligenceConfigRequest,
    GetProjectIntelligenceConfigRequest,
    GetStorageLayoutRequest,
    IntelligenceConfig,
    ListAnywhereCachesRequest,
    ListAnywhereCachesResponse,
    ListFoldersRequest,
    ListFoldersResponse,
    ListManagedFoldersRequest,
    ListManagedFoldersResponse,
    ManagedFolder,
    PauseAnywhereCacheRequest,
    PendingRenameInfo,
    RenameFolderMetadata,
    RenameFolderRequest,
    ResumeAnywhereCacheRequest,
    StorageLayout,
    UpdateAnywhereCacheMetadata,
    UpdateAnywhereCacheRequest,
    UpdateFolderIntelligenceConfigRequest,
    UpdateOrganizationIntelligenceConfigRequest,
    UpdateProjectIntelligenceConfigRequest,
)

__version__ = ...
if sys.version_info >= (3, 8):
    ...
else:
    ...
if hasattr(api_core, "check_python_version") and hasattr(
    api_core, "check_dependency_versions"
):
    ...
else:
    _py_version_str = ...
    _package_label = ...
    def parse_version_to_tuple(version_string: str):  # -> tuple[Any, ...]:
        """Safely converts a semantic version string to a comparable tuple of integers.
        Example: "4.25.8" -> (4, 25, 8)
        Ignores non-numeric parts and handles common version formats.
        Args:
            version_string: Version string in the format "x.y.z" or "x.y.z<suffix>"
        Returns:
            Tuple of integers for the parsed version string.
        """
        ...
    _dependency_package = ...
    _next_supported_version = ...
    _next_supported_version_tuple = ...
    _recommendation = ...
__all__ = (
    "StorageControlAsyncClient",
    "AnywhereCache",
    "CommonLongRunningOperationMetadata",
    "CreateAnywhereCacheMetadata",
    "CreateAnywhereCacheRequest",
    "CreateFolderRequest",
    "CreateManagedFolderRequest",
    "DeleteFolderRequest",
    "DeleteManagedFolderRequest",
    "DisableAnywhereCacheRequest",
    "Folder",
    "GetAnywhereCacheRequest",
    "GetFolderIntelligenceConfigRequest",
    "GetFolderRequest",
    "GetManagedFolderRequest",
    "GetOrganizationIntelligenceConfigRequest",
    "GetProjectIntelligenceConfigRequest",
    "GetStorageLayoutRequest",
    "IntelligenceConfig",
    "ListAnywhereCachesRequest",
    "ListAnywhereCachesResponse",
    "ListFoldersRequest",
    "ListFoldersResponse",
    "ListManagedFoldersRequest",
    "ListManagedFoldersResponse",
    "ManagedFolder",
    "PauseAnywhereCacheRequest",
    "PendingRenameInfo",
    "RenameFolderMetadata",
    "RenameFolderRequest",
    "ResumeAnywhereCacheRequest",
    "StorageControlClient",
    "StorageLayout",
    "UpdateAnywhereCacheMetadata",
    "UpdateAnywhereCacheRequest",
    "UpdateFolderIntelligenceConfigRequest",
    "UpdateOrganizationIntelligenceConfigRequest",
    "UpdateProjectIntelligenceConfigRequest",
)
