{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nglab.fullname" . }}-secrets
  labels:
    {{- include "nglab.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | default (randAlphaNum 32) | quote }}
  {{- if .Values.secrets.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.grafanaPassword }}
  grafana-password: {{ .Values.secrets.grafanaPassword | quote }}
  {{- end }}
{{- end }}
