from typing import Any

import numpy as np

class Arena:
    """The main simulation environment."""

    def __init__(self) -> None: ...
    def step_count(self) -> int: ...

class OrderBook:
    """Central Limit Order Book (CLOB) simulator."""

    def __init__(self) -> None: ...
    def best_bid(self) -> float: ...
    def best_ask(self) -> float: ...
    def mid_price(self) -> float: ...
    def spread(self) -> float: ...
    def imbalance(self) -> float: ...
    def total_bid_volume(self) -> float: ...
    def total_ask_volume(self) -> float: ...

class PolymarketArena:
    """Polymarket trading arena for simulation and backtesting."""

    def __init__(self, initial_collateral: float, taker_fee: float) -> None: ...
    def account_value(self) -> float: ...
    def collateral(self) -> float: ...
    def realized_pnl(self) -> float: ...
    def current_step(self) -> int: ...
    def num_markets(self) -> int: ...
    def load_markets(self, json_data: str) -> None: ...
    def load_price_history(self, market_id: str, csv_data: str) -> None: ...
    def reset(self, initial_collateral: float) -> None: ...
    def get_price(self, market_id: str) -> float | None: ...
    def get_position(self, market_id: str) -> tuple[float, float]: ...
    def buy_yes(self, market_id: str, amount: float) -> float: ...
    def buy_no(self, market_id: str, amount: float) -> float: ...
    def sell_yes(self, market_id: str, amount: float) -> float: ...
    def split(self, market_id: str, amount: float) -> float: ...
    def merge(self, market_id: str, amount: float) -> float: ...
    def advance(self) -> bool: ...

class TradingEnv:
    """
    Trading environment with Gymnasium interface.
    Wraps market simulation logic into a standard RL format.
    """

    def __init__(
        self,
        initial_capital: float = 10000.0,
        transaction_cost: float = 0.001,
        lookback: int = 30,
        max_steps: int = 1000,
        enable_logging: bool = True,
    ) -> None: ...
    def reset(
        self, seed: int | None = None, options: dict[str, Any] | None = None
    ) -> tuple[np.ndarray[Any, Any], dict[str, Any]]: ...
    def step(
        self, action: int
    ) -> tuple[np.ndarray[Any, Any], float, bool, bool, dict[str, Any]]: ...
    def load_prices(self, prices: list[float]) -> None: ...
    def get_observation(self) -> np.ndarray[Any, Any]: ...
