"""
This type stub file was generated by pyright.
"""

"""Shared utilities used by both downloads and uploads.

This utilities are explicitly catered to ``requests``-like transports.
"""
_SINGLE_GET_CHUNK_SIZE = ...
_DEFAULT_CONNECT_TIMEOUT = ...
_DEFAULT_READ_TIMEOUT = ...

class RequestsMixin:
    """Mix-in class implementing ``requests``-specific behavior.

    These are methods that are more general purpose, with implementations
    specific to the types defined in ``requests``.
    """

    ...

class RawRequestsMixin(RequestsMixin): ...

def wait_and_retry(func, retry_strategy):
    """Attempts to retry a call to ``func`` until success.

    Args:
        func (Callable): A callable that takes no arguments and produces
            an HTTP response which will be checked as retry-able.
        retry_strategy (Optional[google.api_core.retry.Retry]): The
            strategy to use if the request fails and must be retried.

    Returns:
        object: The return value of ``func``.
    """
    ...
