"""
This type stub file was generated by pyright.
"""

"""Helpers for Agent Identity credentials."""
_LOGGER = ...
CRYPTOGRAPHY_NOT_FOUND_ERROR = ...
_AGENT_IDENTITY_SPIFFE_TRUST_DOMAIN_PATTERNS = ...
_WELL_KNOWN_CERT_PATH = ...
_FAST_POLL_CYCLES = ...
_FAST_POLL_INTERVAL = ...
_SLOW_POLL_INTERVAL = ...
_TOTAL_TIMEOUT = ...
_SLOW_POLL_CYCLES = ...
_POLLING_INTERVALS = ...
def get_agent_identity_certificate_path(): # -> Any | LiteralString | None:
    """Gets the certificate path from the certificate config file.

    The path to the certificate config file is read from the
    GOOGLE_API_CERTIFICATE_CONFIG environment variable. This function
    implements a retry mechanism to handle cases where the environment
    variable is set before the files are available on the filesystem.

    Returns:
        str: The path to the leaf certificate file.

    Raises:
        google.auth.exceptions.RefreshError: If the certificate config file
            or the certificate file cannot be found after retries.
    """
    ...

def get_and_parse_agent_identity_certificate(): # -> Certificate | None:
    """Gets and parses the agent identity certificate if not opted out.

    Checks if the user has opted out of certificate-bound tokens. If not,
    it gets the certificate path, reads the file, and parses it.

    Returns:
        The parsed certificate object if found and not opted out, otherwise None.
    """
    ...

def parse_certificate(cert_bytes): # -> Certificate:
    """Parses a PEM-encoded certificate.

    Args:
        cert_bytes (bytes): The PEM-encoded certificate bytes.

    Returns:
        cryptography.x509.Certificate: The parsed certificate object.
    """
    ...

def calculate_certificate_fingerprint(cert): # -> str:
    """Calculates the URL-encoded, unpadded, base64-encoded SHA256 hash of a
    DER-encoded certificate.

    Args:
        cert (cryptography.x509.Certificate): The parsed certificate object.

    Returns:
        str: The URL-encoded, unpadded, base64-encoded SHA256 fingerprint.
    """
    ...

def should_request_bound_token(cert): # -> bool:
    """Determines if a bound token should be requested.

    This is based on the GOOGLE_API_PREVENT_AGENT_TOKEN_SHARING_FOR_GCP_SERVICES
    environment variable and whether the certificate is an agent identity cert.

    Args:
        cert (cryptography.x509.Certificate): The parsed certificate object.

    Returns:
        bool: True if a bound token should be requested, False otherwise.
    """
    ...

def call_client_cert_callback(): # -> tuple[Any | None, Any | None]:
    """Calls the client cert callback and returns the certificate and key."""
    ...

def get_cached_cert_fingerprint(cached_cert): # -> str:
    """Returns the fingerprint of the cached certificate."""
    ...

