"""
This type stub file was generated by pyright.
"""

from typing import Callable, MutableSequence, Optional, Sequence, Tuple, Union
from google.api_core import gapic_v1, operation_async
from google.api_core.client_options import ClientOptions
from google.auth import credentials as ga_credentials
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.protobuf import field_mask_pb2
from google.cloud.storage_control_v2.services.storage_control import pagers
from google.cloud.storage_control_v2.types import storage_control
from .client import StorageControlClient
from .transports.base import DEFAULT_CLIENT_INFO, StorageControlTransport

OptionalRetry = ...
CLIENT_LOGGING_SUPPORTED = ...
_LOGGER = ...

class StorageControlAsyncClient:
    """StorageControl service includes selected control plane
    operations.
    """

    _client: StorageControlClient
    DEFAULT_ENDPOINT = ...
    DEFAULT_MTLS_ENDPOINT = StorageControlClient.DEFAULT_MTLS_ENDPOINT
    _DEFAULT_ENDPOINT_TEMPLATE = ...
    _DEFAULT_UNIVERSE = ...
    anywhere_cache_path = ...
    parse_anywhere_cache_path = ...
    folder_path = ...
    parse_folder_path = ...
    intelligence_config_path = ...
    parse_intelligence_config_path = ...
    managed_folder_path = ...
    parse_managed_folder_path = ...
    storage_layout_path = ...
    parse_storage_layout_path = ...
    common_billing_account_path = ...
    parse_common_billing_account_path = ...
    common_folder_path = ...
    parse_common_folder_path = ...
    common_organization_path = ...
    parse_common_organization_path = ...
    common_project_path = ...
    parse_common_project_path = ...
    common_location_path = ...
    parse_common_location_path = ...
    @classmethod
    def from_service_account_info(cls, info: dict, *args, **kwargs):  # -> Any:
        """Creates an instance of this client using the provided credentials
            info.

        Args:
            info (dict): The service account private key info.
            args: Additional arguments to pass to the constructor.
            kwargs: Additional arguments to pass to the constructor.

        Returns:
            StorageControlAsyncClient: The constructed client.
        """
        ...

    @classmethod
    def from_service_account_file(cls, filename: str, *args, **kwargs):  # -> Any:
        """Creates an instance of this client using the provided credentials
            file.

        Args:
            filename (str): The path to the service account private key json
                file.
            args: Additional arguments to pass to the constructor.
            kwargs: Additional arguments to pass to the constructor.

        Returns:
            StorageControlAsyncClient: The constructed client.
        """
        ...
    from_service_account_json = ...
    @classmethod
    def get_mtls_endpoint_and_cert_source(
        cls, client_options: Optional[ClientOptions] = ...
    ):  # -> tuple[Any | Literal['storage.googleapis.com'], Any | None]:
        """Return the API endpoint and client cert source for mutual TLS.

        The client cert source is determined in the following order:
        (1) if `GOOGLE_API_USE_CLIENT_CERTIFICATE` environment variable is not "true", the
        client cert source is None.
        (2) if `client_options.client_cert_source` is provided, use the provided one; if the
        default client cert source exists, use the default one; otherwise the client cert
        source is None.

        The API endpoint is determined in the following order:
        (1) if `client_options.api_endpoint` if provided, use the provided one.
        (2) if `GOOGLE_API_USE_CLIENT_CERTIFICATE` environment variable is "always", use the
        default mTLS endpoint; if the environment variable is "never", use the default API
        endpoint; otherwise if client cert source exists, use the default mTLS endpoint, otherwise
        use the default API endpoint.

        More details can be found at https://google.aip.dev/auth/4114.

        Args:
            client_options (google.api_core.client_options.ClientOptions): Custom options for the
                client. Only the `api_endpoint` and `client_cert_source` properties may be used
                in this method.

        Returns:
            Tuple[str, Callable[[], Tuple[bytes, bytes]]]: returns the API endpoint and the
                client cert source to use.

        Raises:
            google.auth.exceptions.MutualTLSChannelError: If any errors happen.
        """
        ...

    @property
    def transport(self) -> StorageControlTransport:
        """Returns the transport used by the client instance.

        Returns:
            StorageControlTransport: The transport used by the client instance.
        """
        ...

    @property
    def api_endpoint(self):  # -> str | Any | None:
        """Return the API endpoint used by the client instance.

        Returns:
            str: The API endpoint used by the client instance.
        """
        ...

    @property
    def universe_domain(self) -> str:
        """Return the universe domain used by the client instance.

        Returns:
            str: The universe domain used
                by the client instance.
        """
        ...
    get_transport_class = ...
    def __init__(
        self,
        *,
        credentials: Optional[ga_credentials.Credentials] = ...,
        transport: Optional[
            Union[str, StorageControlTransport, Callable[..., StorageControlTransport]]
        ] = ...,
        client_options: Optional[ClientOptions] = ...,
        client_info: gapic_v1.client_info.ClientInfo = ...,
    ) -> None:
        """Instantiates the storage control async client.

        Args:
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            transport (Optional[Union[str,StorageControlTransport,Callable[..., StorageControlTransport]]]):
                The transport to use, or a Callable that constructs and returns a new transport to use.
                If a Callable is given, it will be called with the same set of initialization
                arguments as used in the StorageControlTransport constructor.
                If set to None, a transport is chosen automatically.
            client_options (Optional[Union[google.api_core.client_options.ClientOptions, dict]]):
                Custom options for the client.

                1. The ``api_endpoint`` property can be used to override the
                default endpoint provided by the client when ``transport`` is
                not explicitly provided. Only if this property is not set and
                ``transport`` was not explicitly provided, the endpoint is
                determined by the GOOGLE_API_USE_MTLS_ENDPOINT environment
                variable, which have one of the following values:
                "always" (always use the default mTLS endpoint), "never" (always
                use the default regular endpoint) and "auto" (auto-switch to the
                default mTLS endpoint if client certificate is present; this is
                the default value).

                2. If the GOOGLE_API_USE_CLIENT_CERTIFICATE environment variable
                is "true", then the ``client_cert_source`` property can be used
                to provide a client certificate for mTLS transport. If
                not provided, the default SSL client certificate will be used if
                present. If GOOGLE_API_USE_CLIENT_CERTIFICATE is "false" or not
                set, no client certificate will be used.

                3. The ``universe_domain`` property can be used to override the
                default "googleapis.com" universe. Note that ``api_endpoint``
                property still takes precedence; and ``universe_domain`` is
                currently not supported for mTLS.

            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you're developing
                your own client library.

        Raises:
            google.auth.exceptions.MutualTlsChannelError: If mutual TLS transport
                creation failed for any reason.
        """
        ...

    async def create_folder(
        self,
        request: Optional[Union[storage_control.CreateFolderRequest, dict]] = ...,
        *,
        parent: Optional[str] = ...,
        folder: Optional[storage_control.Folder] = ...,
        folder_id: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.Folder:
        r"""Creates a new folder. This operation is only
        applicable to a hierarchical namespace enabled bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_create_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.CreateFolderRequest(
                    parent="parent_value",
                    folder_id="folder_id_value",
                )

                # Make the request
                response = await client.create_folder(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.CreateFolderRequest, dict]]):
                The request object. Request message for CreateFolder.
                This operation is only applicable to a
                hierarchical namespace enabled bucket.
            parent (:class:`str`):
                Required. Name of the bucket in which
                the folder will reside. The bucket must
                be a hierarchical namespace enabled
                bucket.

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            folder (:class:`google.cloud.storage_control_v2.types.Folder`):
                Required. Properties of the new folder being created.
                The bucket and name of the folder are specified in the
                parent and folder_id fields, respectively. Populating
                those fields in ``folder`` will result in an error.

                This corresponds to the ``folder`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            folder_id (:class:`str`):
                Required. The full name of a folder, including all its
                parent folders. Folders use single '/' characters as a
                delimiter. The folder_id must end with a slash. For
                example, the folder_id of "books/biographies/" would
                create a new "biographies/" folder under the "books/"
                folder.

                This corresponds to the ``folder_id`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.Folder:
                A folder resource. This resource can
                only exist in a hierarchical namespace
                enabled bucket.

        """
        ...

    async def delete_folder(
        self,
        request: Optional[Union[storage_control.DeleteFolderRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        r"""Permanently deletes an empty folder. This operation
        is only applicable to a hierarchical namespace enabled
        bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_delete_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.DeleteFolderRequest(
                    name="name_value",
                )

                # Make the request
                await client.delete_folder(request=request)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.DeleteFolderRequest, dict]]):
                The request object. Request message for DeleteFolder.
                This operation is only applicable to a
                hierarchical namespace enabled bucket.
            name (:class:`str`):
                Required. Name of the folder. Format:
                ``projects/{project}/buckets/{bucket}/folders/{folder}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    async def get_folder(
        self,
        request: Optional[Union[storage_control.GetFolderRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.Folder:
        r"""Returns metadata for the specified folder. This
        operation is only applicable to a hierarchical namespace
        enabled bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetFolderRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_folder(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetFolderRequest, dict]]):
                The request object. Request message for GetFolder. This
                operation is only applicable to a
                hierarchical namespace enabled bucket.
            name (:class:`str`):
                Required. Name of the folder. Format:
                ``projects/{project}/buckets/{bucket}/folders/{folder}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.Folder:
                A folder resource. This resource can
                only exist in a hierarchical namespace
                enabled bucket.

        """
        ...

    async def list_folders(
        self,
        request: Optional[Union[storage_control.ListFoldersRequest, dict]] = ...,
        *,
        parent: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> pagers.ListFoldersAsyncPager:
        r"""Retrieves a list of folders. This operation is only
        applicable to a hierarchical namespace enabled bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_list_folders():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.ListFoldersRequest(
                    parent="parent_value",
                )

                # Make the request
                page_result = client.list_folders(request=request)

                # Handle the response
                async for response in page_result:
                    print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.ListFoldersRequest, dict]]):
                The request object. Request message for ListFolders. This
                operation is only applicable to a
                hierarchical namespace enabled bucket.
            parent (:class:`str`):
                Required. Name of the bucket in which
                to look for folders. The bucket must be
                a hierarchical namespace enabled bucket.

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.services.storage_control.pagers.ListFoldersAsyncPager:
                Response message for ListFolders.

                Iterating over this object will yield
                results and resolve additional pages
                automatically.

        """
        ...

    async def rename_folder(
        self,
        request: Optional[Union[storage_control.RenameFolderRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        destination_folder_id: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> operation_async.AsyncOperation:
        r"""Renames a source folder to a destination folder. This
        operation is only applicable to a hierarchical namespace
        enabled bucket. During a rename, the source and
        destination folders are locked until the long running
        operation completes.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_rename_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.RenameFolderRequest(
                    name="name_value",
                    destination_folder_id="destination_folder_id_value",
                )

                # Make the request
                operation = client.rename_folder(request=request)

                print("Waiting for operation to complete...")

                response = (await operation).result()

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.RenameFolderRequest, dict]]):
                The request object. Request message for RenameFolder.
                This operation is only applicable to a
                hierarchical namespace enabled bucket.
            name (:class:`str`):
                Required. Name of the source folder being renamed.
                Format:
                ``projects/{project}/buckets/{bucket}/folders/{folder}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            destination_folder_id (:class:`str`):
                Required. The destination folder ID, e.g. ``foo/bar/``.
                This corresponds to the ``destination_folder_id`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.api_core.operation_async.AsyncOperation:
                An object representing a long-running operation.

                The result type for the operation will be :class:`google.cloud.storage_control_v2.types.Folder` A folder resource. This resource can only exist in a hierarchical namespace
                   enabled bucket.

        """
        ...

    async def get_storage_layout(
        self,
        request: Optional[Union[storage_control.GetStorageLayoutRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.StorageLayout:
        r"""Returns the storage layout configuration for a given
        bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_storage_layout():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetStorageLayoutRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_storage_layout(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetStorageLayoutRequest, dict]]):
                The request object. Request message for GetStorageLayout.
            name (:class:`str`):
                Required. The name of the StorageLayout resource.
                Format:
                ``projects/{project}/buckets/{bucket}/storageLayout``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.StorageLayout:
                The storage layout configuration of a
                bucket.

        """
        ...

    async def create_managed_folder(
        self,
        request: Optional[
            Union[storage_control.CreateManagedFolderRequest, dict]
        ] = ...,
        *,
        parent: Optional[str] = ...,
        managed_folder: Optional[storage_control.ManagedFolder] = ...,
        managed_folder_id: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.ManagedFolder:
        r"""Creates a new managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_create_managed_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.CreateManagedFolderRequest(
                    parent="parent_value",
                    managed_folder_id="managed_folder_id_value",
                )

                # Make the request
                response = await client.create_managed_folder(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.CreateManagedFolderRequest, dict]]):
                The request object. Request message for
                CreateManagedFolder.
            parent (:class:`str`):
                Required. Name of the bucket this
                managed folder belongs to.

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            managed_folder (:class:`google.cloud.storage_control_v2.types.ManagedFolder`):
                Required. Properties of the managed folder being
                created. The bucket and managed folder names are
                specified in the ``parent`` and ``managed_folder_id``
                fields. Populating these fields in ``managed_folder``
                will result in an error.

                This corresponds to the ``managed_folder`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            managed_folder_id (:class:`str`):
                Required. The name of the managed folder. It uses a
                single ``/`` as delimiter and leading and trailing ``/``
                are allowed.

                This corresponds to the ``managed_folder_id`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.ManagedFolder:
                A managed folder.
        """
        ...

    async def delete_managed_folder(
        self,
        request: Optional[
            Union[storage_control.DeleteManagedFolderRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        r"""Permanently deletes an empty managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_delete_managed_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.DeleteManagedFolderRequest(
                    name="name_value",
                )

                # Make the request
                await client.delete_managed_folder(request=request)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.DeleteManagedFolderRequest, dict]]):
                The request object. DeleteManagedFolder RPC request
                message.
            name (:class:`str`):
                Required. Name of the managed folder. Format:
                ``projects/{project}/buckets/{bucket}/managedFolders/{managedFolder}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    async def get_managed_folder(
        self,
        request: Optional[Union[storage_control.GetManagedFolderRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.ManagedFolder:
        r"""Returns metadata for the specified managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_managed_folder():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetManagedFolderRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_managed_folder(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetManagedFolderRequest, dict]]):
                The request object. Request message for GetManagedFolder.
            name (:class:`str`):
                Required. Name of the managed folder. Format:
                ``projects/{project}/buckets/{bucket}/managedFolders/{managedFolder}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.ManagedFolder:
                A managed folder.
        """
        ...

    async def list_managed_folders(
        self,
        request: Optional[Union[storage_control.ListManagedFoldersRequest, dict]] = ...,
        *,
        parent: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> pagers.ListManagedFoldersAsyncPager:
        r"""Retrieves a list of managed folders for a given
        bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_list_managed_folders():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.ListManagedFoldersRequest(
                    parent="parent_value",
                )

                # Make the request
                page_result = client.list_managed_folders(request=request)

                # Handle the response
                async for response in page_result:
                    print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.ListManagedFoldersRequest, dict]]):
                The request object. Request message for
                ListManagedFolders.
            parent (:class:`str`):
                Required. Name of the bucket this
                managed folder belongs to.

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.services.storage_control.pagers.ListManagedFoldersAsyncPager:
                Response message for
                ListManagedFolders.
                Iterating over this object will yield
                results and resolve additional pages
                automatically.

        """
        ...

    async def create_anywhere_cache(
        self,
        request: Optional[
            Union[storage_control.CreateAnywhereCacheRequest, dict]
        ] = ...,
        *,
        parent: Optional[str] = ...,
        anywhere_cache: Optional[storage_control.AnywhereCache] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> operation_async.AsyncOperation:
        r"""Creates an Anywhere Cache instance.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_create_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.CreateAnywhereCacheRequest(
                    parent="parent_value",
                )

                # Make the request
                operation = client.create_anywhere_cache(request=request)

                print("Waiting for operation to complete...")

                response = (await operation).result()

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.CreateAnywhereCacheRequest, dict]]):
                The request object. Request message for
                CreateAnywhereCache.
            parent (:class:`str`):
                Required. The bucket to which this cache belongs.
                Format: ``projects/{project}/buckets/{bucket}``

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            anywhere_cache (:class:`google.cloud.storage_control_v2.types.AnywhereCache`):
                Required. Properties of the Anywhere Cache instance
                being created. The parent bucket name is specified in
                the ``parent`` field. Server uses the default value of
                ``ttl`` or ``admission_policy`` if not specified in
                request.

                This corresponds to the ``anywhere_cache`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.api_core.operation_async.AsyncOperation:
                An object representing a long-running operation.

                The result type for the operation will be
                :class:`google.cloud.storage_control_v2.types.AnywhereCache`
                An Anywhere Cache Instance.

        """
        ...

    async def update_anywhere_cache(
        self,
        request: Optional[
            Union[storage_control.UpdateAnywhereCacheRequest, dict]
        ] = ...,
        *,
        anywhere_cache: Optional[storage_control.AnywhereCache] = ...,
        update_mask: Optional[field_mask_pb2.FieldMask] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> operation_async.AsyncOperation:
        r"""Updates an Anywhere Cache instance. Mutable fields include
        ``ttl`` and ``admission_policy``.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_update_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.UpdateAnywhereCacheRequest(
                )

                # Make the request
                operation = client.update_anywhere_cache(request=request)

                print("Waiting for operation to complete...")

                response = (await operation).result()

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.UpdateAnywhereCacheRequest, dict]]):
                The request object. Request message for
                UpdateAnywhereCache.
            anywhere_cache (:class:`google.cloud.storage_control_v2.types.AnywhereCache`):
                Required. The Anywhere Cache instance
                to be updated.

                This corresponds to the ``anywhere_cache`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            update_mask (:class:`google.protobuf.field_mask_pb2.FieldMask`):
                Required. List of fields to be updated. Mutable fields
                of AnywhereCache include ``ttl`` and
                ``admission_policy``.

                To specify ALL fields, specify a single field with the
                value ``*``. Note: We recommend against doing this. If a
                new field is introduced at a later time, an older client
                updating with the ``*`` may accidentally reset the new
                field's value.

                Not specifying any fields is an error.

                This corresponds to the ``update_mask`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.api_core.operation_async.AsyncOperation:
                An object representing a long-running operation.

                The result type for the operation will be
                :class:`google.cloud.storage_control_v2.types.AnywhereCache`
                An Anywhere Cache Instance.

        """
        ...

    async def disable_anywhere_cache(
        self,
        request: Optional[
            Union[storage_control.DisableAnywhereCacheRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.AnywhereCache:
        r"""Disables an Anywhere Cache instance. A disabled
        instance is read-only. The disablement could be revoked
        by calling ResumeAnywhereCache. The cache instance will
        be deleted automatically if it remains in the disabled
        state for at least one hour.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_disable_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.DisableAnywhereCacheRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.disable_anywhere_cache(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.DisableAnywhereCacheRequest, dict]]):
                The request object. Request message for
                DisableAnywhereCache.
            name (:class:`str`):
                Required. The name field in the request should be:
                ``projects/{project}/buckets/{bucket}/anywhereCaches/{anywhere_cache}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.AnywhereCache:
                An Anywhere Cache Instance.
        """
        ...

    async def pause_anywhere_cache(
        self,
        request: Optional[Union[storage_control.PauseAnywhereCacheRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.AnywhereCache:
        r"""Pauses an Anywhere Cache instance.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_pause_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.PauseAnywhereCacheRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.pause_anywhere_cache(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.PauseAnywhereCacheRequest, dict]]):
                The request object. Request message for
                PauseAnywhereCache.
            name (:class:`str`):
                Required. The name field in the request should be:
                ``projects/{project}/buckets/{bucket}/anywhereCaches/{anywhere_cache}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.AnywhereCache:
                An Anywhere Cache Instance.
        """
        ...

    async def resume_anywhere_cache(
        self,
        request: Optional[
            Union[storage_control.ResumeAnywhereCacheRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.AnywhereCache:
        r"""Resumes a disabled or paused Anywhere Cache instance.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_resume_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.ResumeAnywhereCacheRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.resume_anywhere_cache(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.ResumeAnywhereCacheRequest, dict]]):
                The request object. Request message for
                ResumeAnywhereCache.
            name (:class:`str`):
                Required. The name field in the request should be:
                ``projects/{project}/buckets/{bucket}/anywhereCaches/{anywhere_cache}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.AnywhereCache:
                An Anywhere Cache Instance.
        """
        ...

    async def get_anywhere_cache(
        self,
        request: Optional[Union[storage_control.GetAnywhereCacheRequest, dict]] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.AnywhereCache:
        r"""Gets an Anywhere Cache instance.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_anywhere_cache():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetAnywhereCacheRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_anywhere_cache(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetAnywhereCacheRequest, dict]]):
                The request object. Request message for GetAnywhereCache.
            name (:class:`str`):
                Required. The name field in the request should be:
                ``projects/{project}/buckets/{bucket}/anywhereCaches/{anywhere_cache}``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.AnywhereCache:
                An Anywhere Cache Instance.
        """
        ...

    async def list_anywhere_caches(
        self,
        request: Optional[Union[storage_control.ListAnywhereCachesRequest, dict]] = ...,
        *,
        parent: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> pagers.ListAnywhereCachesAsyncPager:
        r"""Lists Anywhere Cache instances for a given bucket.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_list_anywhere_caches():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.ListAnywhereCachesRequest(
                    parent="parent_value",
                )

                # Make the request
                page_result = client.list_anywhere_caches(request=request)

                # Handle the response
                async for response in page_result:
                    print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.ListAnywhereCachesRequest, dict]]):
                The request object. Request message for
                ListAnywhereCaches.
            parent (:class:`str`):
                Required. The bucket to which this
                cache belongs.

                This corresponds to the ``parent`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.services.storage_control.pagers.ListAnywhereCachesAsyncPager:
                Response message for
                ListAnywhereCaches.
                Iterating over this object will yield
                results and resolve additional pages
                automatically.

        """
        ...

    async def get_project_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.GetProjectIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Returns the Project scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_project_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetProjectIntelligenceConfigRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_project_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetProjectIntelligenceConfigRequest, dict]]):
                The request object. Request message to get the ``IntelligenceConfig``
                resource associated with your project.

                **IAM Permissions**:

                Requires ``storage.intelligenceConfigs.get``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the project.
            name (:class:`str`):
                Required. The name of the ``IntelligenceConfig``
                resource associated with your project.

                Format:
                ``projects/{id}/locations/global/intelligenceConfig``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def update_project_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.UpdateProjectIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        intelligence_config: Optional[storage_control.IntelligenceConfig] = ...,
        update_mask: Optional[field_mask_pb2.FieldMask] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Updates the Project scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_update_project_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.UpdateProjectIntelligenceConfigRequest(
                )

                # Make the request
                response = await client.update_project_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.UpdateProjectIntelligenceConfigRequest, dict]]):
                The request object. Request message to update the ``IntelligenceConfig``
                resource associated with your project.

                **IAM Permissions**:

                Requires ``storage.intelligenceConfigs.update``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the folder.
            intelligence_config (:class:`google.cloud.storage_control_v2.types.IntelligenceConfig`):
                Required. The ``IntelligenceConfig`` resource to be
                updated.

                This corresponds to the ``intelligence_config`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            update_mask (:class:`google.protobuf.field_mask_pb2.FieldMask`):
                Required. The ``update_mask`` that specifies the fields
                within the ``IntelligenceConfig`` resource that should
                be modified by this update. Only the listed fields are
                updated.

                This corresponds to the ``update_mask`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def get_folder_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.GetFolderIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Returns the Folder scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_folder_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetFolderIntelligenceConfigRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_folder_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetFolderIntelligenceConfigRequest, dict]]):
                The request object. Request message to get the ``IntelligenceConfig``
                resource associated with your folder.

                **IAM Permissions**

                Requires ``storage.intelligenceConfigs.get``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the folder.
            name (:class:`str`):
                Required. The name of the ``IntelligenceConfig``
                resource associated with your folder.

                Format:
                ``folders/{id}/locations/global/intelligenceConfig``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def update_folder_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.UpdateFolderIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        intelligence_config: Optional[storage_control.IntelligenceConfig] = ...,
        update_mask: Optional[field_mask_pb2.FieldMask] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Updates the Folder scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_update_folder_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.UpdateFolderIntelligenceConfigRequest(
                )

                # Make the request
                response = await client.update_folder_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.UpdateFolderIntelligenceConfigRequest, dict]]):
                The request object. Request message to update the ``IntelligenceConfig``
                resource associated with your folder.

                **IAM Permissions**:

                Requires ``storage.intelligenceConfigs.update``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the folder.
            intelligence_config (:class:`google.cloud.storage_control_v2.types.IntelligenceConfig`):
                Required. The ``IntelligenceConfig`` resource to be
                updated.

                This corresponds to the ``intelligence_config`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            update_mask (:class:`google.protobuf.field_mask_pb2.FieldMask`):
                Required. The ``update_mask`` that specifies the fields
                within the ``IntelligenceConfig`` resource that should
                be modified by this update. Only the listed fields are
                updated.

                This corresponds to the ``update_mask`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def get_organization_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.GetOrganizationIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        name: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Returns the Organization scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_get_organization_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.GetOrganizationIntelligenceConfigRequest(
                    name="name_value",
                )

                # Make the request
                response = await client.get_organization_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.GetOrganizationIntelligenceConfigRequest, dict]]):
                The request object. Request message to get the ``IntelligenceConfig``
                resource associated with your organization.

                **IAM Permissions**

                Requires ``storage.intelligenceConfigs.get``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the organization.
            name (:class:`str`):
                Required. The name of the ``IntelligenceConfig``
                resource associated with your organization.

                Format:
                ``organizations/{org_id}/locations/global/intelligenceConfig``

                This corresponds to the ``name`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def update_organization_intelligence_config(
        self,
        request: Optional[
            Union[storage_control.UpdateOrganizationIntelligenceConfigRequest, dict]
        ] = ...,
        *,
        intelligence_config: Optional[storage_control.IntelligenceConfig] = ...,
        update_mask: Optional[field_mask_pb2.FieldMask] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> storage_control.IntelligenceConfig:
        r"""Updates the Organization scoped singleton
        IntelligenceConfig resource.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2

            async def sample_update_organization_intelligence_config():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = storage_control_v2.UpdateOrganizationIntelligenceConfigRequest(
                )

                # Make the request
                response = await client.update_organization_intelligence_config(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.cloud.storage_control_v2.types.UpdateOrganizationIntelligenceConfigRequest, dict]]):
                The request object. Request message to update the ``IntelligenceConfig``
                resource associated with your organization.

                **IAM Permissions**:

                Requires ``storage.intelligenceConfigs.update``
                `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                permission on the organization.
            intelligence_config (:class:`google.cloud.storage_control_v2.types.IntelligenceConfig`):
                Required. The ``IntelligenceConfig`` resource to be
                updated.

                This corresponds to the ``intelligence_config`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            update_mask (:class:`google.protobuf.field_mask_pb2.FieldMask`):
                Required. The ``update_mask`` that specifies the fields
                within the ``IntelligenceConfig`` resource that should
                be modified by this update. Only the listed fields are
                updated.

                This corresponds to the ``update_mask`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.cloud.storage_control_v2.types.IntelligenceConfig:
                The IntelligenceConfig resource associated with your organization, folder,
                   or project.

        """
        ...

    async def get_iam_policy(
        self,
        request: Optional[Union[iam_policy_pb2.GetIamPolicyRequest, dict]] = ...,
        *,
        resource: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> policy_pb2.Policy:
        r"""Gets the IAM policy for a specified bucket. The ``resource``
        field in the request should be ``projects/_/buckets/{bucket}``
        for a bucket, or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2
            from google.iam.v1 import iam_policy_pb2  # type: ignore

            async def sample_get_iam_policy():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = iam_policy_pb2.GetIamPolicyRequest(
                    resource="resource_value",
                )

                # Make the request
                response = await client.get_iam_policy(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.iam.v1.iam_policy_pb2.GetIamPolicyRequest, dict]]):
                The request object. Request message for ``GetIamPolicy`` method.
            resource (:class:`str`):
                REQUIRED: The resource for which the
                policy is being requested. See the
                operation documentation for the
                appropriate value for this field.

                This corresponds to the ``resource`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.iam.v1.policy_pb2.Policy:
                An Identity and Access Management (IAM) policy, which specifies access
                   controls for Google Cloud resources.

                   A Policy is a collection of bindings. A binding binds
                   one or more members, or principals, to a single role.
                   Principals can be user accounts, service accounts,
                   Google groups, and domains (such as G Suite). A role
                   is a named list of permissions; each role can be an
                   IAM predefined role or a user-created custom role.

                   For some types of Google Cloud resources, a binding
                   can also specify a condition, which is a logical
                   expression that allows access to a resource only if
                   the expression evaluates to true. A condition can add
                   constraints based on attributes of the request, the
                   resource, or both. To learn which resources support
                   conditions in their IAM policies, see the [IAM
                   documentation](https://cloud.google.com/iam/help/conditions/resource-policies).

                   **JSON example:**

                   :literal:``     {       "bindings": [         {           "role": "roles/resourcemanager.organizationAdmin",           "members": [             "user:mike@example.com",             "group:admins@example.com",             "domain:google.com",             "serviceAccount:my-project-id@appspot.gserviceaccount.com"           ]         },         {           "role": "roles/resourcemanager.organizationViewer",           "members": [             "user:eve@example.com"           ],           "condition": {             "title": "expirable access",             "description": "Does not grant access after Sep 2020",             "expression": "request.time <             timestamp('2020-10-01T00:00:00.000Z')",           }         }       ],       "etag": "BwWWja0YfJA=",       "version": 3     }`\ \`

                   **YAML example:**

                   :literal:``     bindings:     - members:       - user:mike@example.com       - group:admins@example.com       - domain:google.com       - serviceAccount:my-project-id@appspot.gserviceaccount.com       role: roles/resourcemanager.organizationAdmin     - members:       - user:eve@example.com       role: roles/resourcemanager.organizationViewer       condition:         title: expirable access         description: Does not grant access after Sep 2020         expression: request.time < timestamp('2020-10-01T00:00:00.000Z')     etag: BwWWja0YfJA=     version: 3`\ \`

                   For a description of IAM and its features, see the
                   [IAM
                   documentation](https://cloud.google.com/iam/docs/).

        """
        ...

    async def set_iam_policy(
        self,
        request: Optional[Union[iam_policy_pb2.SetIamPolicyRequest, dict]] = ...,
        *,
        resource: Optional[str] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> policy_pb2.Policy:
        r"""Updates an IAM policy for the specified bucket. The ``resource``
        field in the request should be ``projects/_/buckets/{bucket}``
        for a bucket, or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2
            from google.iam.v1 import iam_policy_pb2  # type: ignore

            async def sample_set_iam_policy():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = iam_policy_pb2.SetIamPolicyRequest(
                    resource="resource_value",
                )

                # Make the request
                response = await client.set_iam_policy(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.iam.v1.iam_policy_pb2.SetIamPolicyRequest, dict]]):
                The request object. Request message for ``SetIamPolicy`` method.
            resource (:class:`str`):
                REQUIRED: The resource for which the
                policy is being specified. See the
                operation documentation for the
                appropriate value for this field.

                This corresponds to the ``resource`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.iam.v1.policy_pb2.Policy:
                An Identity and Access Management (IAM) policy, which specifies access
                   controls for Google Cloud resources.

                   A Policy is a collection of bindings. A binding binds
                   one or more members, or principals, to a single role.
                   Principals can be user accounts, service accounts,
                   Google groups, and domains (such as G Suite). A role
                   is a named list of permissions; each role can be an
                   IAM predefined role or a user-created custom role.

                   For some types of Google Cloud resources, a binding
                   can also specify a condition, which is a logical
                   expression that allows access to a resource only if
                   the expression evaluates to true. A condition can add
                   constraints based on attributes of the request, the
                   resource, or both. To learn which resources support
                   conditions in their IAM policies, see the [IAM
                   documentation](https://cloud.google.com/iam/help/conditions/resource-policies).

                   **JSON example:**

                   :literal:``     {       "bindings": [         {           "role": "roles/resourcemanager.organizationAdmin",           "members": [             "user:mike@example.com",             "group:admins@example.com",             "domain:google.com",             "serviceAccount:my-project-id@appspot.gserviceaccount.com"           ]         },         {           "role": "roles/resourcemanager.organizationViewer",           "members": [             "user:eve@example.com"           ],           "condition": {             "title": "expirable access",             "description": "Does not grant access after Sep 2020",             "expression": "request.time <             timestamp('2020-10-01T00:00:00.000Z')",           }         }       ],       "etag": "BwWWja0YfJA=",       "version": 3     }`\ \`

                   **YAML example:**

                   :literal:``     bindings:     - members:       - user:mike@example.com       - group:admins@example.com       - domain:google.com       - serviceAccount:my-project-id@appspot.gserviceaccount.com       role: roles/resourcemanager.organizationAdmin     - members:       - user:eve@example.com       role: roles/resourcemanager.organizationViewer       condition:         title: expirable access         description: Does not grant access after Sep 2020         expression: request.time < timestamp('2020-10-01T00:00:00.000Z')     etag: BwWWja0YfJA=     version: 3`\ \`

                   For a description of IAM and its features, see the
                   [IAM
                   documentation](https://cloud.google.com/iam/docs/).

        """
        ...

    async def test_iam_permissions(
        self,
        request: Optional[Union[iam_policy_pb2.TestIamPermissionsRequest, dict]] = ...,
        *,
        resource: Optional[str] = ...,
        permissions: Optional[MutableSequence[str]] = ...,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> iam_policy_pb2.TestIamPermissionsResponse:
        r"""Tests a set of permissions on the given bucket, object, or
        managed folder to see which, if any, are held by the caller. The
        ``resource`` field in the request should be
        ``projects/_/buckets/{bucket}`` for a bucket,
        ``projects/_/buckets/{bucket}/objects/{object}`` for an object,
        or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        .. code-block:: python

            # This snippet has been automatically generated and should be regarded as a
            # code template only.
            # It will require modifications to work:
            # - It may require correct/in-range values for request initialization.
            # - It may require specifying regional endpoints when creating the service
            #   client as shown in:
            #   https://googleapis.dev/python/google-api-core/latest/client_options.html
            from google.cloud import storage_control_v2
            from google.iam.v1 import iam_policy_pb2  # type: ignore

            async def sample_test_iam_permissions():
                # Create a client
                client = storage_control_v2.StorageControlAsyncClient()

                # Initialize request argument(s)
                request = iam_policy_pb2.TestIamPermissionsRequest(
                    resource="resource_value",
                    permissions=['permissions_value1', 'permissions_value2'],
                )

                # Make the request
                response = await client.test_iam_permissions(request=request)

                # Handle the response
                print(response)

        Args:
            request (Optional[Union[google.iam.v1.iam_policy_pb2.TestIamPermissionsRequest, dict]]):
                The request object. Request message for ``TestIamPermissions`` method.
            resource (:class:`str`):
                REQUIRED: The resource for which the
                policy detail is being requested. See
                the operation documentation for the
                appropriate value for this field.

                This corresponds to the ``resource`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            permissions (:class:`MutableSequence[str]`):
                The set of permissions to check for the ``resource``.
                Permissions with wildcards (such as '*' or 'storage.*')
                are not allowed. For more information see `IAM
                Overview <https://cloud.google.com/iam/docs/overview#permissions>`__.

                This corresponds to the ``permissions`` field
                on the ``request`` instance; if ``request`` is provided, this
                should not be set.
            retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.

        Returns:
            google.iam.v1.iam_policy_pb2.TestIamPermissionsResponse:
                Response message for TestIamPermissions method.
        """
        ...

    async def __aenter__(self) -> StorageControlAsyncClient: ...
    async def __aexit__(self, exc_type, exc, tb):  # -> None:
        ...

DEFAULT_CLIENT_INFO = ...
if hasattr(DEFAULT_CLIENT_INFO, "protobuf_runtime_version"): ...
__all__ = ("StorageControlAsyncClient",)
