"""
This type stub file was generated by pyright.
"""

from typing import (
    Any,
    AsyncIterator,
    Awaitable,
    Callable,
    Iterator,
    Sequence,
    Tuple,
    Union,
)
from google.cloud.storage_control_v2.types import storage_control

OptionalRetry = ...
OptionalAsyncRetry = ...

class ListFoldersPager:
    """A pager for iterating through ``list_folders`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListFoldersResponse` object, and
    provides an ``__iter__`` method to iterate through its
    ``folders`` field.

    If there are more pages, the ``__iter__`` method will make additional
    ``ListFolders`` requests and continue to iterate
    through the ``folders`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListFoldersResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., storage_control.ListFoldersResponse],
        request: storage_control.ListFoldersRequest,
        response: storage_control.ListFoldersResponse,
        *,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiate the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListFoldersRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListFoldersResponse):
                The initial response object.
            retry (google.api_core.retry.Retry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    def pages(self) -> Iterator[storage_control.ListFoldersResponse]: ...
    def __iter__(self) -> Iterator[storage_control.Folder]: ...
    def __repr__(self) -> str: ...

class ListFoldersAsyncPager:
    """A pager for iterating through ``list_folders`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListFoldersResponse` object, and
    provides an ``__aiter__`` method to iterate through its
    ``folders`` field.

    If there are more pages, the ``__aiter__`` method will make additional
    ``ListFolders`` requests and continue to iterate
    through the ``folders`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListFoldersResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., Awaitable[storage_control.ListFoldersResponse]],
        request: storage_control.ListFoldersRequest,
        response: storage_control.ListFoldersResponse,
        *,
        retry: OptionalAsyncRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiates the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListFoldersRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListFoldersResponse):
                The initial response object.
            retry (google.api_core.retry.AsyncRetry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    async def pages(self) -> AsyncIterator[storage_control.ListFoldersResponse]: ...
    def __aiter__(self) -> AsyncIterator[storage_control.Folder]: ...
    def __repr__(self) -> str: ...

class ListManagedFoldersPager:
    """A pager for iterating through ``list_managed_folders`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListManagedFoldersResponse` object, and
    provides an ``__iter__`` method to iterate through its
    ``managed_folders`` field.

    If there are more pages, the ``__iter__`` method will make additional
    ``ListManagedFolders`` requests and continue to iterate
    through the ``managed_folders`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListManagedFoldersResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., storage_control.ListManagedFoldersResponse],
        request: storage_control.ListManagedFoldersRequest,
        response: storage_control.ListManagedFoldersResponse,
        *,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiate the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListManagedFoldersRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListManagedFoldersResponse):
                The initial response object.
            retry (google.api_core.retry.Retry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    def pages(self) -> Iterator[storage_control.ListManagedFoldersResponse]: ...
    def __iter__(self) -> Iterator[storage_control.ManagedFolder]: ...
    def __repr__(self) -> str: ...

class ListManagedFoldersAsyncPager:
    """A pager for iterating through ``list_managed_folders`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListManagedFoldersResponse` object, and
    provides an ``__aiter__`` method to iterate through its
    ``managed_folders`` field.

    If there are more pages, the ``__aiter__`` method will make additional
    ``ListManagedFolders`` requests and continue to iterate
    through the ``managed_folders`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListManagedFoldersResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., Awaitable[storage_control.ListManagedFoldersResponse]],
        request: storage_control.ListManagedFoldersRequest,
        response: storage_control.ListManagedFoldersResponse,
        *,
        retry: OptionalAsyncRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiates the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListManagedFoldersRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListManagedFoldersResponse):
                The initial response object.
            retry (google.api_core.retry.AsyncRetry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    async def pages(
        self,
    ) -> AsyncIterator[storage_control.ListManagedFoldersResponse]: ...
    def __aiter__(self) -> AsyncIterator[storage_control.ManagedFolder]: ...
    def __repr__(self) -> str: ...

class ListAnywhereCachesPager:
    """A pager for iterating through ``list_anywhere_caches`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListAnywhereCachesResponse` object, and
    provides an ``__iter__`` method to iterate through its
    ``anywhere_caches`` field.

    If there are more pages, the ``__iter__`` method will make additional
    ``ListAnywhereCaches`` requests and continue to iterate
    through the ``anywhere_caches`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListAnywhereCachesResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., storage_control.ListAnywhereCachesResponse],
        request: storage_control.ListAnywhereCachesRequest,
        response: storage_control.ListAnywhereCachesResponse,
        *,
        retry: OptionalRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiate the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListAnywhereCachesRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListAnywhereCachesResponse):
                The initial response object.
            retry (google.api_core.retry.Retry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    def pages(self) -> Iterator[storage_control.ListAnywhereCachesResponse]: ...
    def __iter__(self) -> Iterator[storage_control.AnywhereCache]: ...
    def __repr__(self) -> str: ...

class ListAnywhereCachesAsyncPager:
    """A pager for iterating through ``list_anywhere_caches`` requests.

    This class thinly wraps an initial
    :class:`google.cloud.storage_control_v2.types.ListAnywhereCachesResponse` object, and
    provides an ``__aiter__`` method to iterate through its
    ``anywhere_caches`` field.

    If there are more pages, the ``__aiter__`` method will make additional
    ``ListAnywhereCaches`` requests and continue to iterate
    through the ``anywhere_caches`` field on the
    corresponding responses.

    All the usual :class:`google.cloud.storage_control_v2.types.ListAnywhereCachesResponse`
    attributes are available on the pager. If multiple requests are made, only
    the most recent response is retained, and thus used for attribute lookup.
    """

    def __init__(
        self,
        method: Callable[..., Awaitable[storage_control.ListAnywhereCachesResponse]],
        request: storage_control.ListAnywhereCachesRequest,
        response: storage_control.ListAnywhereCachesResponse,
        *,
        retry: OptionalAsyncRetry = ...,
        timeout: Union[float, object] = ...,
        metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
    ) -> None:
        """Instantiates the pager.

        Args:
            method (Callable): The method that was originally called, and
                which instantiated this pager.
            request (google.cloud.storage_control_v2.types.ListAnywhereCachesRequest):
                The initial request object.
            response (google.cloud.storage_control_v2.types.ListAnywhereCachesResponse):
                The initial response object.
            retry (google.api_core.retry.AsyncRetry): Designation of what errors,
                if any, should be retried.
            timeout (float): The timeout for this request.
            metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                sent along with the request as metadata. Normally, each value must be of type `str`,
                but for metadata keys ending with the suffix `-bin`, the corresponding values must
                be of type `bytes`.
        """
        ...

    def __getattr__(self, name: str) -> Any: ...
    @property
    async def pages(
        self,
    ) -> AsyncIterator[storage_control.ListAnywhereCachesResponse]: ...
    def __aiter__(self) -> AsyncIterator[storage_control.AnywhereCache]: ...
    def __repr__(self) -> str: ...
