"""
This type stub file was generated by pyright.
"""

from google.cloud.storage._media.common import UPLOAD_CHUNK_SIZE

"""Utilities for Google Media Downloads and Resumable Uploads.

===========
Subpackages
===========

Each subpackage is tailored to a specific transport library:

* the :mod:`~google.cloud.storage._media.requests` subpackage uses the ``requests``
  transport library.

.. _requests: http://docs.python-requests.org/
"""
__all__ = ["UPLOAD_CHUNK_SIZE"]
