"""
This type stub file was generated by pyright.
"""

"""Common utilities for Google Media Downloads and Resumable Uploads.

Includes custom exception types, useful constants and shared helpers.
"""
UPLOAD_CHUNK_SIZE = ...
