"""
This type stub file was generated by pyright.
"""

import abc
from typing import Awaitable, Callable, Optional, Sequence, Union
from google.api_core import gapic_v1
from google.auth import credentials as ga_credentials
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.longrunning import operations_pb2
from google.protobuf import empty_pb2
from google.cloud.storage_control_v2.types import storage_control

DEFAULT_CLIENT_INFO = ...
if hasattr(DEFAULT_CLIENT_INFO, "protobuf_runtime_version"):
    ...
class StorageControlTransport(abc.ABC):
    """Abstract transport class for StorageControl."""
    AUTH_SCOPES = ...
    DEFAULT_HOST: str = ...
    def __init__(self, *, host: str = ..., credentials: Optional[ga_credentials.Credentials] = ..., credentials_file: Optional[str] = ..., scopes: Optional[Sequence[str]] = ..., quota_project_id: Optional[str] = ..., client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: Optional[bool] = ..., api_audience: Optional[str] = ..., **kwargs) -> None:
        """Instantiate the transport.

        Args:
            host (Optional[str]):
                 The hostname to connect to (default: 'storage.googleapis.com').
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            credentials_file (Optional[str]): Deprecated. A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`.
                This argument is mutually exclusive with credentials. This argument will be
                removed in the next major version of this library.
            scopes (Optional[Sequence[str]]): A list of scopes.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you're developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.
        """
        ...
    
    @property
    def host(self): # -> str:
        ...
    
    def close(self):
        """Closes resources associated with the transport.

        .. warning::
             Only call this method if the transport is NOT shared
             with other clients - this may cause errors in other clients!
        """
        ...
    
    @property
    def operations_client(self):
        """Return the client designed to process long-running operations."""
        ...
    
    @property
    def create_folder(self) -> Callable[[storage_control.CreateFolderRequest], Union[storage_control.Folder, Awaitable[storage_control.Folder]],]:
        ...
    
    @property
    def delete_folder(self) -> Callable[[storage_control.DeleteFolderRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def get_folder(self) -> Callable[[storage_control.GetFolderRequest], Union[storage_control.Folder, Awaitable[storage_control.Folder]],]:
        ...
    
    @property
    def list_folders(self) -> Callable[[storage_control.ListFoldersRequest], Union[storage_control.ListFoldersResponse, Awaitable[storage_control.ListFoldersResponse],],]:
        ...
    
    @property
    def rename_folder(self) -> Callable[[storage_control.RenameFolderRequest], Union[operations_pb2.Operation, Awaitable[operations_pb2.Operation]],]:
        ...
    
    @property
    def get_storage_layout(self) -> Callable[[storage_control.GetStorageLayoutRequest], Union[storage_control.StorageLayout, Awaitable[storage_control.StorageLayout]],]:
        ...
    
    @property
    def create_managed_folder(self) -> Callable[[storage_control.CreateManagedFolderRequest], Union[storage_control.ManagedFolder, Awaitable[storage_control.ManagedFolder]],]:
        ...
    
    @property
    def delete_managed_folder(self) -> Callable[[storage_control.DeleteManagedFolderRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def get_managed_folder(self) -> Callable[[storage_control.GetManagedFolderRequest], Union[storage_control.ManagedFolder, Awaitable[storage_control.ManagedFolder]],]:
        ...
    
    @property
    def list_managed_folders(self) -> Callable[[storage_control.ListManagedFoldersRequest], Union[storage_control.ListManagedFoldersResponse, Awaitable[storage_control.ListManagedFoldersResponse],],]:
        ...
    
    @property
    def create_anywhere_cache(self) -> Callable[[storage_control.CreateAnywhereCacheRequest], Union[operations_pb2.Operation, Awaitable[operations_pb2.Operation]],]:
        ...
    
    @property
    def update_anywhere_cache(self) -> Callable[[storage_control.UpdateAnywhereCacheRequest], Union[operations_pb2.Operation, Awaitable[operations_pb2.Operation]],]:
        ...
    
    @property
    def disable_anywhere_cache(self) -> Callable[[storage_control.DisableAnywhereCacheRequest], Union[storage_control.AnywhereCache, Awaitable[storage_control.AnywhereCache]],]:
        ...
    
    @property
    def pause_anywhere_cache(self) -> Callable[[storage_control.PauseAnywhereCacheRequest], Union[storage_control.AnywhereCache, Awaitable[storage_control.AnywhereCache]],]:
        ...
    
    @property
    def resume_anywhere_cache(self) -> Callable[[storage_control.ResumeAnywhereCacheRequest], Union[storage_control.AnywhereCache, Awaitable[storage_control.AnywhereCache]],]:
        ...
    
    @property
    def get_anywhere_cache(self) -> Callable[[storage_control.GetAnywhereCacheRequest], Union[storage_control.AnywhereCache, Awaitable[storage_control.AnywhereCache]],]:
        ...
    
    @property
    def list_anywhere_caches(self) -> Callable[[storage_control.ListAnywhereCachesRequest], Union[storage_control.ListAnywhereCachesResponse, Awaitable[storage_control.ListAnywhereCachesResponse],],]:
        ...
    
    @property
    def get_project_intelligence_config(self) -> Callable[[storage_control.GetProjectIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def update_project_intelligence_config(self) -> Callable[[storage_control.UpdateProjectIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def get_folder_intelligence_config(self) -> Callable[[storage_control.GetFolderIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def update_folder_intelligence_config(self) -> Callable[[storage_control.UpdateFolderIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def get_organization_intelligence_config(self) -> Callable[[storage_control.GetOrganizationIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def update_organization_intelligence_config(self) -> Callable[[storage_control.UpdateOrganizationIntelligenceConfigRequest], Union[storage_control.IntelligenceConfig, Awaitable[storage_control.IntelligenceConfig],],]:
        ...
    
    @property
    def get_iam_policy(self) -> Callable[[iam_policy_pb2.GetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def set_iam_policy(self) -> Callable[[iam_policy_pb2.SetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def test_iam_permissions(self) -> Callable[[iam_policy_pb2.TestIamPermissionsRequest], Union[iam_policy_pb2.TestIamPermissionsResponse, Awaitable[iam_policy_pb2.TestIamPermissionsResponse],],]:
        ...
    
    @property
    def kind(self) -> str:
        ...
    


__all__ = ("StorageControlTransport", )
