"""
This type stub file was generated by pyright.
"""

import grpc
from typing import Awaitable, Callable, Dict, Optional, Sequence, Tuple, Union
from google.api_core import gapic_v1, operations_v1
from google.auth import credentials as ga_credentials
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.longrunning import operations_pb2
from google.protobuf import empty_pb2
from grpc.experimental import aio
from google.cloud.storage_control_v2.types import storage_control
from .base import StorageControlTransport

CLIENT_LOGGING_SUPPORTED = ...
_LOGGER = ...

class _LoggingClientAIOInterceptor(grpc.aio.UnaryUnaryClientInterceptor):
    async def intercept_unary_unary(
        self, continuation, client_call_details, request
    ):  # -> UnaryUnaryCall[Any, Any]:
        ...

class StorageControlGrpcAsyncIOTransport(StorageControlTransport):
    """gRPC AsyncIO backend transport for StorageControl.

    StorageControl service includes selected control plane
    operations.

    This class defines the same methods as the primary client, so the
    primary client can load the underlying transport implementation
    and call it.

    It sends protocol buffers over the wire using gRPC (which is built on
    top of HTTP/2); the ``grpcio`` package must be installed.
    """

    _grpc_channel: aio.Channel
    _stubs: Dict[str, Callable] = ...
    @classmethod
    def create_channel(
        cls,
        host: str = ...,
        credentials: Optional[ga_credentials.Credentials] = ...,
        credentials_file: Optional[str] = ...,
        scopes: Optional[Sequence[str]] = ...,
        quota_project_id: Optional[str] = ...,
        **kwargs,
    ) -> aio.Channel:
        """Create and return a gRPC AsyncIO channel object.
        Args:
            host (Optional[str]): The host for the channel to use.
            credentials (Optional[~.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify this application to the service. If
                none are specified, the client will attempt to ascertain
                the credentials from the environment.
            credentials_file (Optional[str]): Deprecated. A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`. This argument will be
                removed in the next major version of this library.
            scopes (Optional[Sequence[str]]): A optional list of scopes needed for this
                service. These are only used when credentials are not specified and
                are passed to :func:`google.auth.default`.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            kwargs (Optional[dict]): Keyword arguments, which are passed to the
                channel creation.
        Returns:
            aio.Channel: A gRPC AsyncIO channel object.
        """
        ...

    def __init__(
        self,
        *,
        host: str = ...,
        credentials: Optional[ga_credentials.Credentials] = ...,
        credentials_file: Optional[str] = ...,
        scopes: Optional[Sequence[str]] = ...,
        channel: Optional[Union[aio.Channel, Callable[..., aio.Channel]]] = ...,
        api_mtls_endpoint: Optional[str] = ...,
        client_cert_source: Optional[Callable[[], Tuple[bytes, bytes]]] = ...,
        ssl_channel_credentials: Optional[grpc.ChannelCredentials] = ...,
        client_cert_source_for_mtls: Optional[Callable[[], Tuple[bytes, bytes]]] = ...,
        quota_project_id: Optional[str] = ...,
        client_info: gapic_v1.client_info.ClientInfo = ...,
        always_use_jwt_access: Optional[bool] = ...,
        api_audience: Optional[str] = ...,
    ) -> None:
        """Instantiate the transport.

        Args:
            host (Optional[str]):
                 The hostname to connect to (default: 'storage.googleapis.com').
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
                This argument is ignored if a ``channel`` instance is provided.
            credentials_file (Optional[str]): Deprecated. A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`.
                This argument is ignored if a ``channel`` instance is provided.
                This argument will be removed in the next major version of this library.
            scopes (Optional[Sequence[str]]): A optional list of scopes needed for this
                service. These are only used when credentials are not specified and
                are passed to :func:`google.auth.default`.
            channel (Optional[Union[aio.Channel, Callable[..., aio.Channel]]]):
                A ``Channel`` instance through which to make calls, or a Callable
                that constructs and returns one. If set to None, ``self.create_channel``
                is used to create the channel. If a Callable is given, it will be called
                with the same arguments as used in ``self.create_channel``.
            api_mtls_endpoint (Optional[str]): Deprecated. The mutual TLS endpoint.
                If provided, it overrides the ``host`` argument and tries to create
                a mutual TLS channel with client SSL credentials from
                ``client_cert_source`` or application default SSL credentials.
            client_cert_source (Optional[Callable[[], Tuple[bytes, bytes]]]):
                Deprecated. A callback to provide client SSL certificate bytes and
                private key bytes, both in PEM format. It is ignored if
                ``api_mtls_endpoint`` is None.
            ssl_channel_credentials (grpc.ChannelCredentials): SSL credentials
                for the grpc channel. It is ignored if a ``channel`` instance is provided.
            client_cert_source_for_mtls (Optional[Callable[[], Tuple[bytes, bytes]]]):
                A callback to provide client certificate bytes and private key bytes,
                both in PEM format. It is used to configure a mutual TLS channel. It is
                ignored if a ``channel`` instance or ``ssl_channel_credentials`` is provided.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you're developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.

        Raises:
            google.auth.exceptions.MutualTlsChannelError: If mutual TLS transport
              creation failed for any reason.
          google.api_core.exceptions.DuplicateCredentialArgs: If both ``credentials``
              and ``credentials_file`` are passed.
        """
        ...

    @property
    def grpc_channel(self) -> aio.Channel:
        """Create the channel designed to connect to this service.

        This property caches on the instance; repeated calls return
        the same channel.
        """
        ...

    @property
    def operations_client(self) -> operations_v1.OperationsAsyncClient:
        """Create the client designed to process long-running operations.

        This property caches on the instance; repeated calls return the same
        client.
        """
        ...

    @property
    def create_folder(
        self,
    ) -> Callable[
        [storage_control.CreateFolderRequest], Awaitable[storage_control.Folder]
    ]:
        r"""Return a callable for the create folder method over gRPC.

        Creates a new folder. This operation is only
        applicable to a hierarchical namespace enabled bucket.

        Returns:
            Callable[[~.CreateFolderRequest],
                    Awaitable[~.Folder]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def delete_folder(
        self,
    ) -> Callable[[storage_control.DeleteFolderRequest], Awaitable[empty_pb2.Empty]]:
        r"""Return a callable for the delete folder method over gRPC.

        Permanently deletes an empty folder. This operation
        is only applicable to a hierarchical namespace enabled
        bucket.

        Returns:
            Callable[[~.DeleteFolderRequest],
                    Awaitable[~.Empty]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_folder(
        self,
    ) -> Callable[
        [storage_control.GetFolderRequest], Awaitable[storage_control.Folder]
    ]:
        r"""Return a callable for the get folder method over gRPC.

        Returns metadata for the specified folder. This
        operation is only applicable to a hierarchical namespace
        enabled bucket.

        Returns:
            Callable[[~.GetFolderRequest],
                    Awaitable[~.Folder]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def list_folders(
        self,
    ) -> Callable[
        [storage_control.ListFoldersRequest],
        Awaitable[storage_control.ListFoldersResponse],
    ]:
        r"""Return a callable for the list folders method over gRPC.

        Retrieves a list of folders. This operation is only
        applicable to a hierarchical namespace enabled bucket.

        Returns:
            Callable[[~.ListFoldersRequest],
                    Awaitable[~.ListFoldersResponse]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def rename_folder(
        self,
    ) -> Callable[
        [storage_control.RenameFolderRequest], Awaitable[operations_pb2.Operation]
    ]:
        r"""Return a callable for the rename folder method over gRPC.

        Renames a source folder to a destination folder. This
        operation is only applicable to a hierarchical namespace
        enabled bucket. During a rename, the source and
        destination folders are locked until the long running
        operation completes.

        Returns:
            Callable[[~.RenameFolderRequest],
                    Awaitable[~.Operation]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_storage_layout(
        self,
    ) -> Callable[
        [storage_control.GetStorageLayoutRequest],
        Awaitable[storage_control.StorageLayout],
    ]:
        r"""Return a callable for the get storage layout method over gRPC.

        Returns the storage layout configuration for a given
        bucket.

        Returns:
            Callable[[~.GetStorageLayoutRequest],
                    Awaitable[~.StorageLayout]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def create_managed_folder(
        self,
    ) -> Callable[
        [storage_control.CreateManagedFolderRequest],
        Awaitable[storage_control.ManagedFolder],
    ]:
        r"""Return a callable for the create managed folder method over gRPC.

        Creates a new managed folder.

        Returns:
            Callable[[~.CreateManagedFolderRequest],
                    Awaitable[~.ManagedFolder]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def delete_managed_folder(
        self,
    ) -> Callable[
        [storage_control.DeleteManagedFolderRequest], Awaitable[empty_pb2.Empty]
    ]:
        r"""Return a callable for the delete managed folder method over gRPC.

        Permanently deletes an empty managed folder.

        Returns:
            Callable[[~.DeleteManagedFolderRequest],
                    Awaitable[~.Empty]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_managed_folder(
        self,
    ) -> Callable[
        [storage_control.GetManagedFolderRequest],
        Awaitable[storage_control.ManagedFolder],
    ]:
        r"""Return a callable for the get managed folder method over gRPC.

        Returns metadata for the specified managed folder.

        Returns:
            Callable[[~.GetManagedFolderRequest],
                    Awaitable[~.ManagedFolder]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def list_managed_folders(
        self,
    ) -> Callable[
        [storage_control.ListManagedFoldersRequest],
        Awaitable[storage_control.ListManagedFoldersResponse],
    ]:
        r"""Return a callable for the list managed folders method over gRPC.

        Retrieves a list of managed folders for a given
        bucket.

        Returns:
            Callable[[~.ListManagedFoldersRequest],
                    Awaitable[~.ListManagedFoldersResponse]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def create_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.CreateAnywhereCacheRequest],
        Awaitable[operations_pb2.Operation],
    ]:
        r"""Return a callable for the create anywhere cache method over gRPC.

        Creates an Anywhere Cache instance.

        Returns:
            Callable[[~.CreateAnywhereCacheRequest],
                    Awaitable[~.Operation]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def update_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.UpdateAnywhereCacheRequest],
        Awaitable[operations_pb2.Operation],
    ]:
        r"""Return a callable for the update anywhere cache method over gRPC.

        Updates an Anywhere Cache instance. Mutable fields include
        ``ttl`` and ``admission_policy``.

        Returns:
            Callable[[~.UpdateAnywhereCacheRequest],
                    Awaitable[~.Operation]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def disable_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.DisableAnywhereCacheRequest],
        Awaitable[storage_control.AnywhereCache],
    ]:
        r"""Return a callable for the disable anywhere cache method over gRPC.

        Disables an Anywhere Cache instance. A disabled
        instance is read-only. The disablement could be revoked
        by calling ResumeAnywhereCache. The cache instance will
        be deleted automatically if it remains in the disabled
        state for at least one hour.

        Returns:
            Callable[[~.DisableAnywhereCacheRequest],
                    Awaitable[~.AnywhereCache]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def pause_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.PauseAnywhereCacheRequest],
        Awaitable[storage_control.AnywhereCache],
    ]:
        r"""Return a callable for the pause anywhere cache method over gRPC.

        Pauses an Anywhere Cache instance.

        Returns:
            Callable[[~.PauseAnywhereCacheRequest],
                    Awaitable[~.AnywhereCache]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def resume_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.ResumeAnywhereCacheRequest],
        Awaitable[storage_control.AnywhereCache],
    ]:
        r"""Return a callable for the resume anywhere cache method over gRPC.

        Resumes a disabled or paused Anywhere Cache instance.

        Returns:
            Callable[[~.ResumeAnywhereCacheRequest],
                    Awaitable[~.AnywhereCache]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.GetAnywhereCacheRequest],
        Awaitable[storage_control.AnywhereCache],
    ]:
        r"""Return a callable for the get anywhere cache method over gRPC.

        Gets an Anywhere Cache instance.

        Returns:
            Callable[[~.GetAnywhereCacheRequest],
                    Awaitable[~.AnywhereCache]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def list_anywhere_caches(
        self,
    ) -> Callable[
        [storage_control.ListAnywhereCachesRequest],
        Awaitable[storage_control.ListAnywhereCachesResponse],
    ]:
        r"""Return a callable for the list anywhere caches method over gRPC.

        Lists Anywhere Cache instances for a given bucket.

        Returns:
            Callable[[~.ListAnywhereCachesRequest],
                    Awaitable[~.ListAnywhereCachesResponse]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_project_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.GetProjectIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the get project intelligence
        config method over gRPC.

        Returns the Project scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.GetProjectIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def update_project_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.UpdateProjectIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the update project intelligence
        config method over gRPC.

        Updates the Project scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.UpdateProjectIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_folder_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.GetFolderIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the get folder intelligence config method over gRPC.

        Returns the Folder scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.GetFolderIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def update_folder_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.UpdateFolderIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the update folder intelligence
        config method over gRPC.

        Updates the Folder scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.UpdateFolderIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_organization_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.GetOrganizationIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the get organization intelligence
        config method over gRPC.

        Returns the Organization scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.GetOrganizationIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def update_organization_intelligence_config(
        self,
    ) -> Callable[
        [storage_control.UpdateOrganizationIntelligenceConfigRequest],
        Awaitable[storage_control.IntelligenceConfig],
    ]:
        r"""Return a callable for the update organization
        intelligence config method over gRPC.

        Updates the Organization scoped singleton
        IntelligenceConfig resource.

        Returns:
            Callable[[~.UpdateOrganizationIntelligenceConfigRequest],
                    Awaitable[~.IntelligenceConfig]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def get_iam_policy(
        self,
    ) -> Callable[[iam_policy_pb2.GetIamPolicyRequest], Awaitable[policy_pb2.Policy]]:
        r"""Return a callable for the get iam policy method over gRPC.

        Gets the IAM policy for a specified bucket. The ``resource``
        field in the request should be ``projects/_/buckets/{bucket}``
        for a bucket, or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        Returns:
            Callable[[~.GetIamPolicyRequest],
                    Awaitable[~.Policy]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def set_iam_policy(
        self,
    ) -> Callable[[iam_policy_pb2.SetIamPolicyRequest], Awaitable[policy_pb2.Policy]]:
        r"""Return a callable for the set iam policy method over gRPC.

        Updates an IAM policy for the specified bucket. The ``resource``
        field in the request should be ``projects/_/buckets/{bucket}``
        for a bucket, or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        Returns:
            Callable[[~.SetIamPolicyRequest],
                    Awaitable[~.Policy]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    @property
    def test_iam_permissions(
        self,
    ) -> Callable[
        [iam_policy_pb2.TestIamPermissionsRequest],
        Awaitable[iam_policy_pb2.TestIamPermissionsResponse],
    ]:
        r"""Return a callable for the test iam permissions method over gRPC.

        Tests a set of permissions on the given bucket, object, or
        managed folder to see which, if any, are held by the caller. The
        ``resource`` field in the request should be
        ``projects/_/buckets/{bucket}`` for a bucket,
        ``projects/_/buckets/{bucket}/objects/{object}`` for an object,
        or
        ``projects/_/buckets/{bucket}/managedFolders/{managedFolder}``
        for a managed folder.

        Returns:
            Callable[[~.TestIamPermissionsRequest],
                    Awaitable[~.TestIamPermissionsResponse]]:
                A function that, when called, will call the underlying RPC
                on the server.
        """
        ...

    def close(self):  # -> CoroutineType[Any, Any, None]:
        ...
    @property
    def kind(self) -> str: ...

__all__ = ("StorageControlGrpcAsyncIOTransport",)
