"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Callable, Optional, Sequence, Tuple, Union
from google.api_core import gapic_v1, operations_v1
from google.auth import credentials as ga_credentials
from google.auth.transport.requests import AuthorizedSession
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.longrunning import operations_pb2
from google.protobuf import empty_pb2
from google.cloud.storage_control_v2.types import storage_control
from .rest_base import _BaseStorageControlRestTransport

OptionalRetry = ...
CLIENT_LOGGING_SUPPORTED = ...
_LOGGER = ...
DEFAULT_CLIENT_INFO = ...
if hasattr(DEFAULT_CLIENT_INFO, "protobuf_runtime_version"):
    ...

class StorageControlRestInterceptor:
    """Interceptor for StorageControl.

    Interceptors are used to manipulate requests, request metadata, and responses
    in arbitrary ways.
    Example use cases include:
    * Logging
    * Verifying requests according to service or custom semantics
    * Stripping extraneous information from responses

    These use cases and more can be enabled by injecting an
    instance of a custom subclass when constructing the StorageControlRestTransport.

    .. code-block:: python
        class MyCustomStorageControlInterceptor(StorageControlRestInterceptor):
            def pre_create_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_create_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_create_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_create_folder(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_create_managed_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_create_managed_folder(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_delete_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def pre_delete_managed_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def pre_disable_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_disable_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_folder(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_folder_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_folder_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_iam_policy(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_iam_policy(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_managed_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_managed_folder(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_organization_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_organization_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_project_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_project_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_get_storage_layout(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_get_storage_layout(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_list_anywhere_caches(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_list_anywhere_caches(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_list_folders(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_list_folders(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_list_managed_folders(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_list_managed_folders(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_pause_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_pause_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_rename_folder(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_rename_folder(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_resume_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_resume_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_set_iam_policy(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_set_iam_policy(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_test_iam_permissions(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_test_iam_permissions(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_update_anywhere_cache(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_update_anywhere_cache(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_update_folder_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_update_folder_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_update_organization_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_update_organization_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

            def pre_update_project_intelligence_config(self, request, metadata):
                logging.log(f"Received request: {request}")
                return request, metadata

            def post_update_project_intelligence_config(self, response):
                logging.log(f"Received response: {response}")
                return response

        transport = StorageControlRestTransport(interceptor=MyCustomStorageControlInterceptor())
        client = StorageControlClient(transport=transport)


    """

    def pre_get_folder_intelligence_config(
        self,
        request: storage_control.GetFolderIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.GetFolderIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for get_folder_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_get_folder_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for get_folder_intelligence_config

        DEPRECATED. Please use the `post_get_folder_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_get_folder_intelligence_config` interceptor runs
        before the `post_get_folder_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_get_folder_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for get_folder_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_get_folder_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_get_folder_intelligence_config` interceptor.
        When both interceptors are used, this `post_get_folder_intelligence_config_with_metadata` interceptor runs after the
        `post_get_folder_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_get_folder_intelligence_config` will be passed to
        `post_get_folder_intelligence_config_with_metadata`.
        """
        ...

    def pre_get_organization_intelligence_config(
        self,
        request: storage_control.GetOrganizationIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.GetOrganizationIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for get_organization_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_get_organization_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for get_organization_intelligence_config

        DEPRECATED. Please use the `post_get_organization_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_get_organization_intelligence_config` interceptor runs
        before the `post_get_organization_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_get_organization_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for get_organization_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_get_organization_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_get_organization_intelligence_config` interceptor.
        When both interceptors are used, this `post_get_organization_intelligence_config_with_metadata` interceptor runs after the
        `post_get_organization_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_get_organization_intelligence_config` will be passed to
        `post_get_organization_intelligence_config_with_metadata`.
        """
        ...

    def pre_get_project_intelligence_config(
        self,
        request: storage_control.GetProjectIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.GetProjectIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for get_project_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_get_project_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for get_project_intelligence_config

        DEPRECATED. Please use the `post_get_project_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_get_project_intelligence_config` interceptor runs
        before the `post_get_project_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_get_project_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for get_project_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_get_project_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_get_project_intelligence_config` interceptor.
        When both interceptors are used, this `post_get_project_intelligence_config_with_metadata` interceptor runs after the
        `post_get_project_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_get_project_intelligence_config` will be passed to
        `post_get_project_intelligence_config_with_metadata`.
        """
        ...

    def pre_update_folder_intelligence_config(
        self,
        request: storage_control.UpdateFolderIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.UpdateFolderIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for update_folder_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_update_folder_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for update_folder_intelligence_config

        DEPRECATED. Please use the `post_update_folder_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_update_folder_intelligence_config` interceptor runs
        before the `post_update_folder_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_update_folder_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for update_folder_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_update_folder_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_update_folder_intelligence_config` interceptor.
        When both interceptors are used, this `post_update_folder_intelligence_config_with_metadata` interceptor runs after the
        `post_update_folder_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_update_folder_intelligence_config` will be passed to
        `post_update_folder_intelligence_config_with_metadata`.
        """
        ...

    def pre_update_organization_intelligence_config(
        self,
        request: storage_control.UpdateOrganizationIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.UpdateOrganizationIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for update_organization_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_update_organization_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for update_organization_intelligence_config

        DEPRECATED. Please use the `post_update_organization_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_update_organization_intelligence_config` interceptor runs
        before the `post_update_organization_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_update_organization_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for update_organization_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_update_organization_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_update_organization_intelligence_config` interceptor.
        When both interceptors are used, this `post_update_organization_intelligence_config_with_metadata` interceptor runs after the
        `post_update_organization_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_update_organization_intelligence_config` will be passed to
        `post_update_organization_intelligence_config_with_metadata`.
        """
        ...

    def pre_update_project_intelligence_config(
        self,
        request: storage_control.UpdateProjectIntelligenceConfigRequest,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.UpdateProjectIntelligenceConfigRequest,
        Sequence[Tuple[str, Union[str, bytes]]],
    ]:
        """Pre-rpc interceptor for update_project_intelligence_config

        Override in a subclass to manipulate the request or metadata
        before they are sent to the StorageControl server.
        """
        ...

    def post_update_project_intelligence_config(
        self, response: storage_control.IntelligenceConfig
    ) -> storage_control.IntelligenceConfig:
        """Post-rpc interceptor for update_project_intelligence_config

        DEPRECATED. Please use the `post_update_project_intelligence_config_with_metadata`
        interceptor instead.

        Override in a subclass to read or manipulate the response
        after it is returned by the StorageControl server but before
        it is returned to user code. This `post_update_project_intelligence_config` interceptor runs
        before the `post_update_project_intelligence_config_with_metadata` interceptor.
        """
        ...

    def post_update_project_intelligence_config_with_metadata(
        self,
        response: storage_control.IntelligenceConfig,
        metadata: Sequence[Tuple[str, Union[str, bytes]]],
    ) -> Tuple[
        storage_control.IntelligenceConfig, Sequence[Tuple[str, Union[str, bytes]]]
    ]:
        """Post-rpc interceptor for update_project_intelligence_config

        Override in a subclass to read or manipulate the response or metadata after it
        is returned by the StorageControl server but before it is returned to user code.

        We recommend only using this `post_update_project_intelligence_config_with_metadata`
        interceptor in new development instead of the `post_update_project_intelligence_config` interceptor.
        When both interceptors are used, this `post_update_project_intelligence_config_with_metadata` interceptor runs after the
        `post_update_project_intelligence_config` interceptor. The (possibly modified) response returned by
        `post_update_project_intelligence_config` will be passed to
        `post_update_project_intelligence_config_with_metadata`.
        """
        ...

@dataclasses.dataclass
class StorageControlRestStub:
    _session: AuthorizedSession
    _host: str
    _interceptor: StorageControlRestInterceptor
    ...

class StorageControlRestTransport(_BaseStorageControlRestTransport):
    """REST backend synchronous transport for StorageControl.

    StorageControl service includes selected control plane
    operations.

    This class defines the same methods as the primary client, so the
    primary client can load the underlying transport implementation
    and call it.

    It sends JSON representations of protocol buffers over HTTP/1.1
    """

    def __init__(
        self,
        *,
        host: str = ...,
        credentials: Optional[ga_credentials.Credentials] = ...,
        credentials_file: Optional[str] = ...,
        scopes: Optional[Sequence[str]] = ...,
        client_cert_source_for_mtls: Optional[Callable[[], Tuple[bytes, bytes]]] = ...,
        quota_project_id: Optional[str] = ...,
        client_info: gapic_v1.client_info.ClientInfo = ...,
        always_use_jwt_access: Optional[bool] = ...,
        url_scheme: str = ...,
        interceptor: Optional[StorageControlRestInterceptor] = ...,
        api_audience: Optional[str] = ...,
    ) -> None:
        """Instantiate the transport.

        Args:
            host (Optional[str]):
                 The hostname to connect to (default: 'storage.googleapis.com').
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.

            credentials_file (Optional[str]): Deprecated. A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`.
                This argument is ignored if ``channel`` is provided. This argument will be
                removed in the next major version of this library.
            scopes (Optional(Sequence[str])): A list of scopes. This argument is
                ignored if ``channel`` is provided.
            client_cert_source_for_mtls (Callable[[], Tuple[bytes, bytes]]): Client
                certificate to configure mutual TLS HTTP channel. It is ignored
                if ``channel`` is provided.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you are developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.
            url_scheme: the protocol scheme for the API endpoint.  Normally
                "https", but for testing or local servers,
                "http" can be specified.
        """
        ...

    @property
    def operations_client(self) -> operations_v1.AbstractOperationsClient:
        """Create the client designed to process long-running operations.

        This property caches on the instance; repeated calls return the same
        client.
        """
        ...

    class _CreateAnywhereCache(
        _BaseStorageControlRestTransport._BaseCreateAnywhereCache,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.CreateAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> operations_pb2.Operation: ...

    class _CreateFolder(
        _BaseStorageControlRestTransport._BaseCreateFolder, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.CreateFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.Folder: ...

    class _CreateManagedFolder(
        _BaseStorageControlRestTransport._BaseCreateManagedFolder,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.CreateManagedFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.ManagedFolder: ...

    class _DeleteFolder(
        _BaseStorageControlRestTransport._BaseDeleteFolder, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.DeleteFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ): ...

    class _DeleteManagedFolder(
        _BaseStorageControlRestTransport._BaseDeleteManagedFolder,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.DeleteManagedFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ): ...

    class _DisableAnywhereCache(
        _BaseStorageControlRestTransport._BaseDisableAnywhereCache,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.DisableAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.AnywhereCache: ...

    class _GetAnywhereCache(
        _BaseStorageControlRestTransport._BaseGetAnywhereCache, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.AnywhereCache: ...

    class _GetFolder(
        _BaseStorageControlRestTransport._BaseGetFolder, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.Folder: ...

    class _GetFolderIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseGetFolderIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetFolderIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the get folder intelligence
            config method over HTTP.

                Args:
                    request (~.storage_control.GetFolderIntelligenceConfigRequest):
                        The request object. Request message to get the ``IntelligenceConfig``
                    resource associated with your folder.

                    **IAM Permissions**

                    Requires ``storage.intelligenceConfigs.get``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the folder.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    class _GetIamPolicy(
        _BaseStorageControlRestTransport._BaseGetIamPolicy, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: iam_policy_pb2.GetIamPolicyRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> policy_pb2.Policy: ...

    class _GetManagedFolder(
        _BaseStorageControlRestTransport._BaseGetManagedFolder, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetManagedFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.ManagedFolder: ...

    class _GetOrganizationIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseGetOrganizationIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetOrganizationIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the get organization
            intelligence config method over HTTP.

                Args:
                    request (~.storage_control.GetOrganizationIntelligenceConfigRequest):
                        The request object. Request message to get the ``IntelligenceConfig``
                    resource associated with your organization.

                    **IAM Permissions**

                    Requires ``storage.intelligenceConfigs.get``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the organization.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    class _GetProjectIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseGetProjectIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetProjectIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the get project intelligence
            config method over HTTP.

                Args:
                    request (~.storage_control.GetProjectIntelligenceConfigRequest):
                        The request object. Request message to get the ``IntelligenceConfig``
                    resource associated with your project.

                    **IAM Permissions**:

                    Requires ``storage.intelligenceConfigs.get``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the project.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    class _GetStorageLayout(
        _BaseStorageControlRestTransport._BaseGetStorageLayout, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.GetStorageLayoutRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.StorageLayout: ...

    class _ListAnywhereCaches(
        _BaseStorageControlRestTransport._BaseListAnywhereCaches, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.ListAnywhereCachesRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.ListAnywhereCachesResponse: ...

    class _ListFolders(
        _BaseStorageControlRestTransport._BaseListFolders, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.ListFoldersRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.ListFoldersResponse: ...

    class _ListManagedFolders(
        _BaseStorageControlRestTransport._BaseListManagedFolders, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.ListManagedFoldersRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.ListManagedFoldersResponse: ...

    class _PauseAnywhereCache(
        _BaseStorageControlRestTransport._BasePauseAnywhereCache, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.PauseAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.AnywhereCache: ...

    class _RenameFolder(
        _BaseStorageControlRestTransport._BaseRenameFolder, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.RenameFolderRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> operations_pb2.Operation: ...

    class _ResumeAnywhereCache(
        _BaseStorageControlRestTransport._BaseResumeAnywhereCache,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.ResumeAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.AnywhereCache: ...

    class _SetIamPolicy(
        _BaseStorageControlRestTransport._BaseSetIamPolicy, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: iam_policy_pb2.SetIamPolicyRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> policy_pb2.Policy: ...

    class _TestIamPermissions(
        _BaseStorageControlRestTransport._BaseTestIamPermissions, StorageControlRestStub
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: iam_policy_pb2.TestIamPermissionsRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> iam_policy_pb2.TestIamPermissionsResponse: ...

    class _UpdateAnywhereCache(
        _BaseStorageControlRestTransport._BaseUpdateAnywhereCache,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.UpdateAnywhereCacheRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> operations_pb2.Operation: ...

    class _UpdateFolderIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseUpdateFolderIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.UpdateFolderIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the update folder
            intelligence config method over HTTP.

                Args:
                    request (~.storage_control.UpdateFolderIntelligenceConfigRequest):
                        The request object. Request message to update the ``IntelligenceConfig``
                    resource associated with your folder.

                    **IAM Permissions**:

                    Requires ``storage.intelligenceConfigs.update``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the folder.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    class _UpdateOrganizationIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseUpdateOrganizationIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.UpdateOrganizationIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the update organization
            intelligence config method over HTTP.

                Args:
                    request (~.storage_control.UpdateOrganizationIntelligenceConfigRequest):
                        The request object. Request message to update the ``IntelligenceConfig``
                    resource associated with your organization.

                    **IAM Permissions**:

                    Requires ``storage.intelligenceConfigs.update``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the organization.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    class _UpdateProjectIntelligenceConfig(
        _BaseStorageControlRestTransport._BaseUpdateProjectIntelligenceConfig,
        StorageControlRestStub,
    ):
        def __hash__(self) -> int: ...
        def __call__(
            self,
            request: storage_control.UpdateProjectIntelligenceConfigRequest,
            *,
            retry: OptionalRetry = ...,
            timeout: Optional[float] = ...,
            metadata: Sequence[Tuple[str, Union[str, bytes]]] = ...,
        ) -> storage_control.IntelligenceConfig:
            r"""Call the update project
            intelligence config method over HTTP.

                Args:
                    request (~.storage_control.UpdateProjectIntelligenceConfigRequest):
                        The request object. Request message to update the ``IntelligenceConfig``
                    resource associated with your project.

                    **IAM Permissions**:

                    Requires ``storage.intelligenceConfigs.update``
                    `IAM <https://cloud.google.com/iam/docs/overview#permissions>`__
                    permission on the folder.
                    retry (google.api_core.retry.Retry): Designation of what errors, if any,
                        should be retried.
                    timeout (float): The timeout for this request.
                    metadata (Sequence[Tuple[str, Union[str, bytes]]]): Key/value pairs which should be
                        sent along with the request as metadata. Normally, each value must be of type `str`,
                        but for metadata keys ending with the suffix `-bin`, the corresponding values must
                        be of type `bytes`.

                Returns:
                    ~.storage_control.IntelligenceConfig:
                        The ``IntelligenceConfig`` resource associated with your
                    organization, folder, or project.

            """
            ...

    @property
    def create_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.CreateAnywhereCacheRequest], operations_pb2.Operation
    ]: ...
    @property
    def create_folder(
        self,
    ) -> Callable[[storage_control.CreateFolderRequest], storage_control.Folder]: ...
    @property
    def create_managed_folder(
        self,
    ) -> Callable[
        [storage_control.CreateManagedFolderRequest], storage_control.ManagedFolder
    ]: ...
    @property
    def delete_folder(
        self,
    ) -> Callable[[storage_control.DeleteFolderRequest], empty_pb2.Empty]: ...
    @property
    def delete_managed_folder(
        self,
    ) -> Callable[[storage_control.DeleteManagedFolderRequest], empty_pb2.Empty]: ...
    @property
    def disable_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.DisableAnywhereCacheRequest], storage_control.AnywhereCache
    ]: ...
    @property
    def get_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.GetAnywhereCacheRequest], storage_control.AnywhereCache
    ]: ...
    @property
    def get_folder(
        self,
    ) -> Callable[[storage_control.GetFolderRequest], storage_control.Folder]: ...
    @property
    def get_folder_intelligence_config(self) -> Callable[
        [storage_control.GetFolderIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def get_iam_policy(
        self,
    ) -> Callable[[iam_policy_pb2.GetIamPolicyRequest], policy_pb2.Policy]: ...
    @property
    def get_managed_folder(
        self,
    ) -> Callable[
        [storage_control.GetManagedFolderRequest], storage_control.ManagedFolder
    ]: ...
    @property
    def get_organization_intelligence_config(self) -> Callable[
        [storage_control.GetOrganizationIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def get_project_intelligence_config(self) -> Callable[
        [storage_control.GetProjectIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def get_storage_layout(
        self,
    ) -> Callable[
        [storage_control.GetStorageLayoutRequest], storage_control.StorageLayout
    ]: ...
    @property
    def list_anywhere_caches(self) -> Callable[
        [storage_control.ListAnywhereCachesRequest],
        storage_control.ListAnywhereCachesResponse,
    ]: ...
    @property
    def list_folders(
        self,
    ) -> Callable[
        [storage_control.ListFoldersRequest], storage_control.ListFoldersResponse
    ]: ...
    @property
    def list_managed_folders(self) -> Callable[
        [storage_control.ListManagedFoldersRequest],
        storage_control.ListManagedFoldersResponse,
    ]: ...
    @property
    def pause_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.PauseAnywhereCacheRequest], storage_control.AnywhereCache
    ]: ...
    @property
    def rename_folder(
        self,
    ) -> Callable[[storage_control.RenameFolderRequest], operations_pb2.Operation]: ...
    @property
    def resume_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.ResumeAnywhereCacheRequest], storage_control.AnywhereCache
    ]: ...
    @property
    def set_iam_policy(
        self,
    ) -> Callable[[iam_policy_pb2.SetIamPolicyRequest], policy_pb2.Policy]: ...
    @property
    def test_iam_permissions(self) -> Callable[
        [iam_policy_pb2.TestIamPermissionsRequest],
        iam_policy_pb2.TestIamPermissionsResponse,
    ]: ...
    @property
    def update_anywhere_cache(
        self,
    ) -> Callable[
        [storage_control.UpdateAnywhereCacheRequest], operations_pb2.Operation
    ]: ...
    @property
    def update_folder_intelligence_config(self) -> Callable[
        [storage_control.UpdateFolderIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def update_organization_intelligence_config(self) -> Callable[
        [storage_control.UpdateOrganizationIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def update_project_intelligence_config(self) -> Callable[
        [storage_control.UpdateProjectIntelligenceConfigRequest],
        storage_control.IntelligenceConfig,
    ]: ...
    @property
    def kind(self) -> str: ...
    def close(self):  # -> None:
        ...

__all__ = ("StorageControlRestTransport",)
